InternexDev_Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Personal Contact Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <label>Funding Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAN_TAN__c</fullName>
        <label>PAN/ TAN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Portal External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>akritiv__Account_Key__c</fullName>
        <defaultValue>TEXT(0)</defaultValue>
        <externalId>true</externalId>
        <label>Account Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Linked_Account__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>akritiv__Brand__c</referenceTo>
        <relationshipLabel>Linked Accounts</relationshipLabel>
        <relationshipName>Linked_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encryption_Key__c</fullName>
        <label>Encryption Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Linked_Account_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Linked Account Type</label>
        <referenceTo>Linked_Account_Type__c</referenceTo>
        <relationshipLabel>Linked Accounts</relationshipLabel>
        <relationshipName>Linked_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portal_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Portal External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>access_token_secret__c</fullName>
        <label>Access Token Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>consumer_key__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>consumer_secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>oauth_token__c</fullName>
        <label>Oauth Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>realm__c</fullName>
        <label>Realm ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Linked Account</label>
    <nameField>
        <displayFormat>LAN-{00000}</displayFormat>
        <label>Linked Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Linked_Account_Type__c.object
<CustomObject>
    <fields>
        <fullName>Portal_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Portal External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Linked Account Type</label>
    <nameField>
        <label>Linked Account Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Linked Account Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/TestQBCustomerandInvoiceBatch.cls
@istest
public class TestQBCustomerandInvoiceBatch
{
    static testmethod void TestBatch()
    {
        Account Acc = new Account();
            Acc.Name ='abc';
            Acc.AccountNumber = '00qsw';
            Acc.akritiv__Account_Key__c = 'key001' ;
            Acc.Funding_Limit__c = 100000;
            Acc.Email__c = 'abc@gmail.com';
            Acc.PAN_TAN__c = '123456789';
            ACC.BillingState = 'NY';
            ACC.BillingPostalCode = '99999';
            Acc.Funding_Limit__c = 100000;
           insert Acc;
        
        akritiv__Brand__C Client = new akritiv__Brand__C();
          Client.CounterParty__c = Acc.Id;
          Client.Name = Acc.Name;
        Client.Portal_External_Id__c='fff333';
    /*      Client.Encryption_Key__c='abc';
          Client.QB_AccessTokenSecret__c ='aaa';
         Client.QB_ConsumerKey__c='ttt';
        Client.QB_OauthToken__c='gsdgdsg';
        Client.QB_Realm__c='dhfh';
        
        Client.QB_ConsumerSecret__c='gggf'; */
        
          insert Client;
        
        Linked_Account_Type__c LAT = new Linked_Account_Type__c();
        LAT.Name = 'QuickBooks';
        insert LAT;
        
        Linked_Account__c LA = new Linked_Account__c();
        LA.Encryption_Key__c='abc';
        LA.access_token_secret__c ='aaa';
        LA.consumer_key__c='ttt';
        LA.oauth_token__c='gsdgdsg';
        LA.realm__c='dhfh';
        LA.consumer_secret__c='gggf';
        LA.Client__c = Client.id;
        LA.Linked_Account_Type__c = LAT.id;
        Insert LA;
        
        Test.startTest();
        SchedulableContext ctx;
        QuickbooksScheduler IB = new QuickbooksScheduler();
        IB.execute(ctx); 
     /*  QBCustomerandInvoiceBatch QB= new QBCustomerandInvoiceBatch();
        Database.executeBatch(QB, 20); 
        Test.stopTest(); */

    }

}