InternexDev_Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Personal Contact Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <label>Funding Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Credit_Period__c</fullName>
        <label>Max Credit Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PAN_TAN__c</fullName>
        <label>PAN/ TAN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_with_Grade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Grade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>akritiv__Account_Key__c</fullName>
        <defaultValue>TEXT(0)</defaultValue>
        <externalId>true</externalId>
        <label>Account Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Client_Account__c.object
<CustomObject>
    <fields>
        <fullName>Borrowing_Base_Reserve__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Borrowing Base Reserve</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>Client__r.Name &amp;&apos;-&apos;&amp; Product__r.Name</formula>
        <inlineHelpText>Client Name &amp;&apos;-&apos;&amp; Product Name</inlineHelpText>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>akritiv__Brand__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commitment__c</fullName>
        <label>Min Utilization (%)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commitment_rate__c</fullName>
        <label>Unused Line Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Drawal_Fee_Percentage__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Drawal_Fee_Percentage__c</defaultValue>
        <label>Draw Fee Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Facility Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Index_Value__c</fullName>
        <label>Index Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <picklist>
            <picklistValues>
                <fullName>Citi Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internex base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LIBOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WS Prime</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>30 / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / ACTUAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Minimum_Drawal_Fee__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Minimum_Drawal_Fee__c</defaultValue>
        <label>Minimum Draw Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Origination_Fee__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Minimum_Origination_Fee__c</defaultValue>
        <label>Minimum Origination Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Origination_Fee_Percentage__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Origination_Fee_Percentage__c</defaultValue>
        <label>Origination Fee Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spread__c</fullName>
        <label>Spread</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sync_with_Grade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Grade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Client Account</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Client Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Debtor__c.object
<CustomObject>
    <fields>
        <fullName>Borrowing_Base_Reserve__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Borrowing Base Reserve</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>Debtors</relationshipLabel>
        <relationshipName>Debtors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Concentration_Limit__c</fullName>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Concentration Limit (%)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Counterparty__c</fullName>
        <label>Debtor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Debtors</relationshipLabel>
        <relationshipName>Debtors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Debtor_Name__c</fullName>
        <formula>TRIM(UPPER(Counterparty__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Debtor Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Debtor_Status__c</fullName>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Debtor Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ineligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirm New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dilution__c</fullName>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Dilution (%)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Eligible_AR__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Eligible AR Limit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Funding Limit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Credit_Period__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Max Credit Period</label>
        <precision>16</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sync_with_Grade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Grade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Debtor</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Debtor Account</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debtor Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Sync_with_Grade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Grade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/testbeforeInsertTrigger.cls
@istest
public class testbeforeInsertTrigger
{
   
    static testmethod void afterInsert()
     {
          Account TestAcc = new Account();
        TestAcc.Name ='Lockbox Account';
        TestAcc.AccountNumber = '00qsw';
        TestAcc.akritiv__Account_Key__c = 'key001' ;
        TestAcc.Funding_Limit__c = 100000;
        TestAcc.Email__c = 'abc@gmail.com';
        TestAcc.PAN_TAN__c = '123456789';
        TestAcc.BillingState = 'NY';
        TestAcc.BillingPostalCode = '99999';
        TestAcc.Funding_Limit__c = 100000;
        insert TestAcc;
        
        Account TestAcc1 = new Account();
        TestAcc1.Name ='acc';
        TestAcc1.AccountNumber = '040qsw';
        TestAcc1.akritiv__Account_Key__c = 'key3001' ;
        TestAcc1.Funding_Limit__c = 500000;
        TestAcc1.Email__c = 'abcd@gmail.com';
        TestAcc1.PAN_TAN__c = '133456789';
        TestAcc1.BillingState = 'NY';
        TestAcc1.BillingPostalCode = '99999';
        TestAcc1.Funding_Limit__c = 300000;
        insert TestAcc1;
        
        
        Product__c testProduct = new Product__c();
        testProduct.Name = 'LOC';
        insert testProduct;
        
        akritiv__Brand__C TestClient = new akritiv__Brand__C();
        TestClient.CounterParty__c = TestAcc.Id;
        TestClient.Name = TestAcc.Name;
        insert TestClient;
        
        Client_Account__c testCA = new Client_Account__c();
        testCA.Client__c = TestClient.Id;
        testCA.Product__c = testProduct.Id;
        testCA.Funding_Limit__c = 100000;
        testCA.Commitment__c = 1000;
        testCA.Commitment_rate__c = 3.5;
        testCA.Index__c = 'WS Prime';
        testCA.Method__c = '360/Actual';
        testCA.Rate_Type__c = 'Fixed';
        testCA.Spread__c = 5;
        testCA.Rate__c = 10;
        testCA.Index_Value__c = 0;
        testCA.Borrowing_Base_Reserve__c = 0;
        testCA.Minimum_Drawal_Fee__c = 100;
        testCA.Minimum_Origination_Fee__c = 100;
        testCA.Drawal_Fee_Percentage__c = 8;
        testCA.Origination_Fee_Percentage__c = 6;
        insert testCA;
        
              
        Debtor__c testdebtor= new Debtor__c();
        //  testdebtor.Debtor_Name__c='FGF3';
        testdebtor.Client_Account__c = testCA.Id;
        testdebtor.Counterparty__c = TestAcc1.Id;
        testdebtor.Dilution__c = 4;
        testdebtor.Funding_Limit__c = 40000;
        testdebtor.Concentration_Limit__c = 40;
        testdebtor.Eligible_AR__c = 2000;
        testdebtor.Borrowing_Base_Reserve__c = 0;
        testdebtor.Max_Credit_Period__c = 80;
        testdebtor.Debtor_Status__c = 'Eligible';
        insert testdebtor;
         
          akritiv__Transaction__c INV = new akritiv__Transaction__c();
        INV.Name = 'TestInv';
        Inv.Debtor__c = testdebtor.id;
        Inv.akritiv__Amount__c = 10000;
        Inv.akritiv__Create_Date__c = date.today();
        Inv.akritiv__Due_Date__c = date.today();
        Inv.Invoice_Status_Internex__c = 'Approved';
       // Inv.Balance_Internex__c=100;
        insert Inv;
         
         
        
      akritiv__Payment__c testPayment = new akritiv__Payment__c();
        testPayment.Name = 'Ankima Payment';
        testPayment.Debtor__c = testdebtor.Id;
        testPayment.Client_Account__c = testCA.Id;
        testPayment.akritiv__Payment_Date__c=Date.today();
        testPayment.akritiv__Amount__c= 15000;
        testPayment.Sync_with_Grade__c= false;
        testPayment.Sync_with_Portal__c=false;
        testPayment.akritiv__Payment_Type__c = 'Manual';
        testPayment.Payment_Status__c='Applied - Processing';
        insert testPayment;
         
         akritiv__Payment_Line__c PL = new akritiv__Payment_Line__c();
        PL.akritiv__Applied_To__c = Inv.id;
        PL.akritiv__Payment__c = testPayment.id;
        PL.Flag_for_Line_Amount__c=true;
          test.startTest();
        insert PL;
         test.stopTest();
         
        
         
         task ta = new task();
         ta.WhatId = testPayment.Id;
         ta.Status='Not Started';
         insert ta;
        

     }
    
   
    static testmethod void Insert1()
     {
        
          Account TestAcc = new Account();
        TestAcc.Name ='Lockbox Account';
        TestAcc.AccountNumber = '00qsw';
        TestAcc.akritiv__Account_Key__c = 'key001' ;
        TestAcc.Funding_Limit__c = 100000;
        TestAcc.Email__c = 'abc@gmail.com';
        TestAcc.PAN_TAN__c = '123456789';
        TestAcc.BillingState = 'NY';
        TestAcc.BillingPostalCode = '99999';
        TestAcc.Funding_Limit__c = 100000;
        insert TestAcc;
        
        Account TestAcc1 = new Account();
        TestAcc1.Name ='acc';
        TestAcc1.AccountNumber = '040qsw';
        TestAcc1.akritiv__Account_Key__c = 'key3001' ;
        TestAcc1.Funding_Limit__c = 500000;
        TestAcc1.Email__c = 'abcd@gmail.com';
        TestAcc1.PAN_TAN__c = '133456789';
        TestAcc1.BillingState = 'NY';
        TestAcc1.BillingPostalCode = '99999';
        TestAcc1.Funding_Limit__c = 300000;
        insert TestAcc1;
        
        
        Product__c testProduct = new Product__c();
        testProduct.Name = 'LOC';
        insert testProduct;
        
        akritiv__Brand__C TestClient = new akritiv__Brand__C();
        TestClient.CounterParty__c = TestAcc.Id;
        TestClient.Name = TestAcc.Name;
        insert TestClient;
        
        Client_Account__c testCA = new Client_Account__c();
        testCA.Client__c = TestClient.Id;
        testCA.Product__c = testProduct.Id;
        testCA.Funding_Limit__c = 100000;
        testCA.Commitment__c = 1000;
        testCA.Commitment_rate__c = 3.5;
        testCA.Index__c = 'WS Prime';
        testCA.Method__c = '360/Actual';
        testCA.Rate_Type__c = 'Fixed';
        testCA.Spread__c = 5;
        testCA.Rate__c = 10;
        testCA.Index_Value__c = 0;
        testCA.Borrowing_Base_Reserve__c = 0;
        testCA.Minimum_Drawal_Fee__c = 100;
        testCA.Minimum_Origination_Fee__c = 100;
        testCA.Drawal_Fee_Percentage__c = 8;
        testCA.Origination_Fee_Percentage__c = 6;
        insert testCA;
        
              
        Debtor__c testdebtor= new Debtor__c();
        //  testdebtor.Debtor_Name__c='FGF3';
        testdebtor.Client_Account__c = testCA.Id;
        testdebtor.Counterparty__c = TestAcc1.Id;
        testdebtor.Dilution__c = 4;
        testdebtor.Funding_Limit__c = 40000;
        testdebtor.Concentration_Limit__c = 40;
        testdebtor.Eligible_AR__c = 2000;
        testdebtor.Borrowing_Base_Reserve__c = 0;
        testdebtor.Max_Credit_Period__c = 80;
        testdebtor.Debtor_Status__c = 'Eligible';
        insert testdebtor;
         
          akritiv__Transaction__c INV = new akritiv__Transaction__c();
        INV.Name = 'TestInv';
        Inv.Debtor__c = testdebtor.id;
        Inv.akritiv__Amount__c = 10000;
        Inv.akritiv__Create_Date__c = date.today();
        Inv.akritiv__Due_Date__c = date.today();
        Inv.Invoice_Status_Internex__c = 'Approved';
       // Inv.Balance_Internex__c=100;
        insert Inv;
        
      akritiv__Payment__c testPayment = new akritiv__Payment__c();
        testPayment.Name = 'Ankima Payment';
        testPayment.Debtor__c = testdebtor.Id;
        testPayment.Client_Account__c = testCA.Id;
        testPayment.akritiv__Payment_Date__c=Date.today();
        testPayment.akritiv__Amount__c= 15000;
        testPayment.Sync_with_Grade__c= false;
        testPayment.Sync_with_Portal__c=false;
        testPayment.Transaction_Type__c='Write Off';
        testPayment.akritiv__Payment_Type__c = 'Manual';
        testPayment.Payment_Status__c='Applied - No Funds';
        insert testPayment;
        testPayment.Payment_Status__c='Applied - Processing';
        update testPayment;
         
          akritiv__Payment_Line__c PL = new akritiv__Payment_Line__c();
        PL.akritiv__Applied_To__c = Inv.id;
        PL.akritiv__Payment__c = testPayment.id;
        PL.Flag_for_Line_Amount__c=True;
          test.startTest();
        insert PL;
         test.stopTest();
        
         
        /* task ta = new task();
         ta.WhatId = testPayment.Id;
         ta.Status='Not Started';
         insert ta;*/
        

    
    }
    
    static testmethod void Insert2()
     {
          Account TestAcc = new Account();
        TestAcc.Name ='Lockbox Account';
        TestAcc.AccountNumber = '00qsw';
        TestAcc.akritiv__Account_Key__c = 'key001' ;
        TestAcc.Funding_Limit__c = 100000;
        TestAcc.Email__c = 'abc@gmail.com';
        TestAcc.PAN_TAN__c = '123456789';
        TestAcc.BillingState = 'NY';
        TestAcc.BillingPostalCode = '99999';
        TestAcc.Funding_Limit__c = 100000;
        insert TestAcc;
        
        Account TestAcc1 = new Account();
        TestAcc1.Name ='acc';
        TestAcc1.AccountNumber = '040qsw';
        TestAcc1.akritiv__Account_Key__c = 'key3001' ;
        TestAcc1.Funding_Limit__c = 500000;
        TestAcc1.Email__c = 'abcd@gmail.com';
        TestAcc1.PAN_TAN__c = '133456789';
        TestAcc1.BillingState = 'NY';
        TestAcc1.BillingPostalCode = '99999';
        TestAcc1.Funding_Limit__c = 300000;
        insert TestAcc1;
        
        
        Product__c testProduct = new Product__c();
        testProduct.Name = 'LOC';
        insert testProduct;
        
        akritiv__Brand__C TestClient = new akritiv__Brand__C();
        TestClient.CounterParty__c = TestAcc.Id;
        TestClient.Name = TestAcc.Name;
        insert TestClient;
        
        Client_Account__c testCA = new Client_Account__c();
        testCA.Client__c = TestClient.Id;
        testCA.Product__c = testProduct.Id;
        testCA.Funding_Limit__c = 100000;
        testCA.Commitment__c = 1000;
        testCA.Commitment_rate__c = 3.5;
        testCA.Index__c = 'WS Prime';
        testCA.Method__c = '360/Actual';
        testCA.Rate_Type__c = 'Fixed';
        testCA.Spread__c = 5;
        testCA.Rate__c = 10;
        testCA.Index_Value__c = 0;
        testCA.Borrowing_Base_Reserve__c = 0;
        testCA.Minimum_Drawal_Fee__c = 100;
        testCA.Minimum_Origination_Fee__c = 100;
        testCA.Drawal_Fee_Percentage__c = 8;
        testCA.Origination_Fee_Percentage__c = 6;
        insert testCA;
        
              
        Debtor__c testdebtor= new Debtor__c();
        //  testdebtor.Debtor_Name__c='FGF3';
        testdebtor.Client_Account__c = testCA.Id;
        testdebtor.Counterparty__c = TestAcc1.Id;
        testdebtor.Dilution__c = 4;
        testdebtor.Funding_Limit__c = 40000;
        testdebtor.Concentration_Limit__c = 40;
        testdebtor.Eligible_AR__c = 2000;
        testdebtor.Borrowing_Base_Reserve__c = 0;
        testdebtor.Max_Credit_Period__c = 80;
        testdebtor.Debtor_Status__c = 'Eligible';
        insert testdebtor;
        
      akritiv__Payment__c testPayment = new akritiv__Payment__c();
        testPayment.Name = 'Ankima Payment';
        testPayment.Debtor__c = testdebtor.Id;
        testPayment.Client_Account__c = testCA.Id;
        testPayment.akritiv__Payment_Date__c=Date.today();
        testPayment.akritiv__Amount__c= 15000;
        testPayment.Sync_with_Grade__c= false;
        testPayment.Sync_with_Portal__c=false;
        testPayment.akritiv__Payment_Type__c = 'Manual';
        testPayment.Payment_Status__c='Applied - Processing';
        insert testPayment;
        testPayment.Sync_with_Portal__c=false;
        update testPayment;
         delete testPayment;
         
         /*task ta = new task();
         ta.WhatId = testPayment.Id;
         ta.Status='Not Started';
         insert ta;*/
        

     }
    static testmethod void afterInsert11()
     {
          Account TestAcc = new Account();
        TestAcc.Name ='Lockbox Account';
        TestAcc.AccountNumber = '00qsw';
        TestAcc.akritiv__Account_Key__c = 'key001' ;
        TestAcc.Funding_Limit__c = 100000;
        TestAcc.Email__c = 'abc@gmail.com';
        TestAcc.PAN_TAN__c = '123456789';
        TestAcc.BillingState = 'NY';
        TestAcc.BillingPostalCode = '99999';
        TestAcc.Funding_Limit__c = 100000;
        insert TestAcc;
        
        Account TestAcc1 = new Account();
        TestAcc1.Name ='acc';
        TestAcc1.AccountNumber = '040qsw';
        TestAcc1.akritiv__Account_Key__c = 'key3001' ;
        TestAcc1.Funding_Limit__c = 500000;
        TestAcc1.Email__c = 'abcd@gmail.com';
        TestAcc1.PAN_TAN__c = '133456789';
        TestAcc1.BillingState = 'NY';
        TestAcc1.BillingPostalCode = '99999';
        TestAcc1.Funding_Limit__c = 300000;
        insert TestAcc1;
        
        
        Product__c testProduct = new Product__c();
        testProduct.Name = 'LOC';
        insert testProduct;
        
        akritiv__Brand__C TestClient = new akritiv__Brand__C();
        TestClient.CounterParty__c = TestAcc.Id;
        TestClient.Name = TestAcc.Name;
        insert TestClient;
        
        Client_Account__c testCA = new Client_Account__c();
        testCA.Client__c = TestClient.Id;
        testCA.Product__c = testProduct.Id;
        testCA.Funding_Limit__c = 100000;
        testCA.Commitment__c = 1000;
        testCA.Commitment_rate__c = 3.5;
        testCA.Index__c = 'WS Prime';
        testCA.Method__c = '360/Actual';
        testCA.Rate_Type__c = 'Fixed';
        testCA.Spread__c = 5;
        testCA.Rate__c = 10;
        testCA.Index_Value__c = 0;
        testCA.Borrowing_Base_Reserve__c = 0;
        testCA.Minimum_Drawal_Fee__c = 100;
        testCA.Minimum_Origination_Fee__c = 100;
        testCA.Drawal_Fee_Percentage__c = 8;
        testCA.Origination_Fee_Percentage__c = 6;
        insert testCA;
        
              
        Debtor__c testdebtor= new Debtor__c();
        //  testdebtor.Debtor_Name__c='FGF3';
        testdebtor.Client_Account__c = testCA.Id;
        testdebtor.Counterparty__c = TestAcc1.Id;
        testdebtor.Dilution__c = 4;
        testdebtor.Funding_Limit__c = 40000;
        testdebtor.Concentration_Limit__c = 40;
        testdebtor.Eligible_AR__c = 2000;
        testdebtor.Borrowing_Base_Reserve__c = 0;
        testdebtor.Max_Credit_Period__c = 80;
        testdebtor.Debtor_Status__c = 'Eligible';
        insert testdebtor;
         
          akritiv__Transaction__c INV = new akritiv__Transaction__c();
        INV.Name = 'TestInv';
        Inv.Debtor__c = testdebtor.id;
        Inv.akritiv__Amount__c = 10000;
        Inv.akritiv__Create_Date__c = date.today();
        Inv.akritiv__Due_Date__c = date.today();
        Inv.Invoice_Status_Internex__c = 'Approved';
       // Inv.Balance_Internex__c=100;
        insert Inv;
         
         
        
      akritiv__Payment__c testPayment = new akritiv__Payment__c();
        testPayment.Name = 'Ankima Payment';
       // testPayment.Debtor__c = testdebtor.Id;
        testPayment.Client_Account__c = testCA.Id;
        testPayment.akritiv__Payment_Date__c=Date.today();
         testPayment.akritiv__Account__c= TestAcc.id;
       // testPayment.akritiv__Amount__c= 15000;
        testPayment.Sync_with_Grade__c= false;
        testPayment.Sync_with_Portal__c=false;
        testPayment.akritiv__Payment_Type__c = 'Manual';
        testPayment.Payment_Status__c='Applied - Processed';
        testPayment.Transaction_Type__c='Write Off';
        testPayment.akritiv__Amount__c=100;
        
        insert testPayment;
         
         akritiv__Payment_Line__c PL = new akritiv__Payment_Line__c();
        PL.akritiv__Applied_To__c = Inv.id;
        PL.akritiv__Payment__c = testPayment.id;
        PL.Flag_for_Line_Amount__c=true;
        PL.akritiv__Applied_Amount__c=50;
          test.startTest();
        insert PL;
         test.stopTest();
         
        
         
         task ta = new task();
         ta.WhatId = testPayment.Id;
         ta.Status='Not Started';
         insert ta;
        

     } 
    

   
}