InternexDev_Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Personal Contact Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <label>Funding Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAN_TAN__c</fullName>
        <label>PAN/ TAN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>akritiv__Account_Key__c</fullName>
        <defaultValue>TEXT(0)</defaultValue>
        <externalId>true</externalId>
        <label>Account Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Client_Account__c.object
<CustomObject>
    <fields>
        <fullName>Borrowing_Base_Reserve__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Borrowing Base Reserve</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>Client__r.Name &amp;&apos;-&apos;&amp; Product__r.Name</formula>
        <inlineHelpText>Client Name &amp;&apos;-&apos;&amp; Product Name</inlineHelpText>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_External_Foreign_Key__c</fullName>
        <description>Created for mapping the Client account and</description>
        <externalId>true</externalId>
        <label>Client External Foreign Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>akritiv__Brand__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commitment__c</fullName>
        <label>Min Utilization (%)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commitment_rate__c</fullName>
        <label>Unused Line Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Drawal_Fee_Percentage__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Drawal_Fee_Percentage__c</defaultValue>
        <label>Draw Fee Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Facility Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IUF_Reserve_Retained__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IUF Reserve Retained</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Index_Value__c</fullName>
        <label>Index Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <picklist>
            <picklistValues>
                <fullName>Citi Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internex base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LIBOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WS Prime</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>30 / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / ACTUAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Minimum_Drawal_Fee__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Minimum_Drawal_Fee__c</defaultValue>
        <label>Minimum Draw Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Origination_Fee__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Minimum_Origination_Fee__c</defaultValue>
        <label>Minimum Origination Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Non_performing_asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Accrual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origination_Fee_Percentage__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Origination_Fee_Percentage__c</defaultValue>
        <label>Origination Fee Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_External_ID__c</fullName>
        <label>Primary Contact External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_External_Foreign_Key__c</fullName>
        <externalId>true</externalId>
        <label>Product External Foreign Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Secondary_Contact_External_Id__c</fullName>
        <label>Secondary Contact External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spread__c</fullName>
        <label>Spread</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Client Account</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Client Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/LockBox_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Routing_Number__c</fullName>
        <formula>Account_Number__c + Routing_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account_Routing_Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>LockBox Accounts</relationshipLabel>
        <relationshipName>LockBoxAccount_CA</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lockbox_Number__c</fullName>
        <label>Lockbox Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing_Number__c</fullName>
        <label>Routing Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LockBox Account</label>
    <nameField>
        <displayFormat>LBA-{0000}</displayFormat>
        <label>LockBox Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LockBoxAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/Test_trgonLockbox.cls
@istest
public class Test_trgonLockbox
{
     static testmethod void trgonLock()
     {
         Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
         testProduct.External_Id__c='ghfhgf7';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
         TestClient.External_Id__c='hghh4';
          insert TestClient;
        
        
        
        Client_Account__c testCA = new Client_Account__c();
          
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
           testCA.Client_External_Foreign_Key__c ='hghh4';
           testCA.Product_External_Foreign_Key__c = 'ghfhgf7';
            testCA.Primary_Contact_External_ID__c='hgf5';
              testCA.Secondary_Contact_External_Id__c='ggg5';
        testCA.Non_performing_asset__c=true;
        testCA.IUF_Reserve_Retained__c=Null;
            insert testCA;
         
          Client_Account__c testCA1 = new Client_Account__c();
          
           testCA1.Client__c = TestClient.Id;
           testCA1.Product__c = testProduct.Id;
           testCA1.Funding_Limit__c = 100000;
           testCA1.Commitment__c = 1000;
           testCA1.Commitment_rate__c = 3.5;
           testCA1.Index__c = 'WS Prime';
           testCA1.Method__c = '360/Actual';
           testCA1.Rate_Type__c = 'Fixed';
           testCA1.Spread__c = 5;
            testCA1.Rate__c = 10;
            testCA1.Index_Value__c = 0;
            testCA1.Borrowing_Base_Reserve__c = 0;
            testCA1.Minimum_Drawal_Fee__c = 100;
            testCA1.Minimum_Origination_Fee__c = 100;
            testCA1.Drawal_Fee_Percentage__c = 8;
            testCA1.Origination_Fee_Percentage__c = 6;
           testCA1.Client_External_Foreign_Key__c ='hghh4';
           testCA1.Product_External_Foreign_Key__c = 'ghfhgf7';
            testCA1.Primary_Contact_External_ID__c='hgf5';
              testCA1.Secondary_Contact_External_Id__c='ggg5';
        testCA1.Non_performing_asset__c=true;
        testCA1.IUF_Reserve_Retained__c=Null;
            insert testCA1;

         
         /*  LockBox_Account__c lock1 = new LockBox_Account__c();
        // lock.Name='lockbox';
         lock1.Account_Number__c='4000161802';
         lock1.Routing_Number__c='121000248';
         lock1.Client_Account__c=testCA.id;
         lock1.Lockbox_Number__c='56565';
         lock1.Street_Address__c='abc';
        // lock.Account_Routing_Number__c='4000161802121000248';
         insert lock1; */
    
         LockBox_Account__c lock = new LockBox_Account__c();
        // lock.Name='lockbox';
         lock.Account_Number__c='1';
         lock.Routing_Number__c='2';
         lock.Client_Account__c=testCA.id;
         lock.Lockbox_Number__c='56565';
         lock.Street_Address__c='abc';
        // lock.Account_Routing_Number__c='12';
         insert lock;
        LockBox_Account__c lock1 = new LockBox_Account__c();
        // lock.Name='lockbox';
         lock1.Account_Number__c='11';
         lock1.Routing_Number__c='22';
         lock1.Client_Account__c=testCA1.id;
         lock1.Lockbox_Number__c='56565';
         lock1.Street_Address__c='abddc';
        // lock.Account_Routing_Number__c='12';
         insert lock1;
     }
    
    static testmethod void trgonLock1()
     {
         Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
         testProduct.External_Id__c='ghfhgf7';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
         TestClient.External_Id__c='hghh4';
          insert TestClient;
        
        
        
        Client_Account__c testCA = new Client_Account__c();
          
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
           testCA.Client_External_Foreign_Key__c ='hghh4';
           testCA.Product_External_Foreign_Key__c = 'ghfhgf7';
            testCA.Primary_Contact_External_ID__c='hgf5';
              testCA.Secondary_Contact_External_Id__c='ggg5';
        testCA.Non_performing_asset__c=true;
        testCA.IUF_Reserve_Retained__c=Null;
            insert testCA;
         
        
    
         LockBox_Account__c lock = new LockBox_Account__c();
        // lock.Name='lockbox';
         lock.Account_Number__c='4000161802';
         lock.Routing_Number__c='121000248';
         lock.Client_Account__c=testCA.id;
         lock.Lockbox_Number__c='56565';
         lock.Street_Address__c='abc';
        // lock.Account_Routing_Number__c='4000161802121000248';
         insert lock;
         lock.Street_Address__c='abcedf'; 
         lock.Account_Number__c='4500161802';
         lock.Routing_Number__c='124000248';
         update lock;
         
     } 
    
    static testmethod void trgonLock2()
     {
         Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
         testProduct.External_Id__c='ghfhgf7';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
         TestClient.External_Id__c='hghh4';
          insert TestClient;
        
        
        
        Client_Account__c testCA = new Client_Account__c();
          
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
           testCA.Client_External_Foreign_Key__c ='hghh4';
           testCA.Product_External_Foreign_Key__c = 'ghfhgf7';
            testCA.Primary_Contact_External_ID__c='hgf5';
              testCA.Secondary_Contact_External_Id__c='ggg5';
        testCA.Non_performing_asset__c=true;
        testCA.IUF_Reserve_Retained__c=Null;
            insert testCA;
    
         LockBox_Account__c lock = new LockBox_Account__c();
        // lock.Name='lockbox';
         lock.Account_Number__c='4000161802';
         lock.Routing_Number__c='121000248';
         lock.Client_Account__c=testCA.id;
         lock.Lockbox_Number__c='56565';
         lock.Street_Address__c='abc';
        // lock.Account_Routing_Number__c='4000161802121000248';
         insert lock;
         
         delete lock;
     }



}