InternexDev_Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Transaction_Date__c</fullName>
        <label>Business Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Brand__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Brand__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Personal Contact Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <label>Funding Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MP_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>MP External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PAN_TAN__c</fullName>
        <label>PAN/ TAN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_ABA__c</fullName>
        <formula>Brand__r.Remit_ABA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remit ABA</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_Account__c</fullName>
        <formula>Brand__r.Remit_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remit Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_Address__c</fullName>
        <formula>Brand__r.Remit_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remit Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_Bank__c</fullName>
        <formula>Brand__r.Remit_Bank__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remit Bank</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_Email__c</fullName>
        <formula>Brand__r.Remit_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remit Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_Name__c</fullName>
        <formula>Brand__r.Remit_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remit Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_PO_Box__c</fullName>
        <formula>Brand__r.Remit_PO_Box__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remit PO Box</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remit_Zip__c</fullName>
        <formula>Brand__r.Remit_Zip__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remit Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Brand__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_with_Grade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Grade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Market_Place__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Market Place</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ZIP_Code__c</fullName>
        <formula>Brand__r.ZIP_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ZIP Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>akritiv__Account_Key__c</fullName>
        <defaultValue>TEXT(0)</defaultValue>
        <externalId>true</externalId>
        <label>Account Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/TestClientSaveAndNew.cls
@istest
public class TestClientSaveAndNew
{
  
   static testmethod void ClientSaveAndNew()
   {
       
            Account Acc = new Account();
            Acc.Name = 'AccountABC';
            Acc.AccountNumber = 'Account Number';
            Acc.akritiv__Account_Key__c = 'ACCKEY' ;
            Acc.Funding_Limit__c = 200000;
            Acc.Email__c = 'TestAcc@testing.com';
            Acc.PAN_TAN__c = '123456789';
            Acc.BillingState = 'IN';
            ACC.BillingPostalCode = '39999';
           insert ACC;
       
       
       
            akritiv__Brand__C Client = new akritiv__Brand__C();
            Client.CounterParty__c = ACC.Id;
            Client.Name = ACC.Name;
          
            Client.Sync_with_Grade__c = false;
            Client.Sync_with_Portal__c = false;
             Client.External_Foreign_Key__c='334rr';
            Client.MP_External_Id__c='rrt5';
            Client.Sync_with_Market_Place__c=True;
            Client.Business_Transaction_Date__c=date.today();
           
            Client.Active__c=True;
            Client.Funding_Limit__c=299;
            Client.City__c='delhi';
            Client.Company_Code__c='ggg';
            Client.Country__c='India';
            Client.Remit_ABA__c='adf';
            Client.Remit_Account__c='ggjj';
            Client.Remit_Address__c='hhjkkl';
            Client.Remit_Bank__c='hhh';
            Client.Remit_Email__c='ankima.g@gmail.com';
            Client.Remit_Name__c='ytrew';
            Client.Remit_PO_Box__c='567yt';
            Client.Remit_Zip__c='ytt555';
            Client.State__c='tttyyy';
            Client.ZIP_Code__c='5656q';
            Client.Application_Number__c='67667ffg';
            Client.Application_Name__c='yyy';
            Client.Referal_Source__c='tyy';
            client.Account__c='hhhhdd';
            client.External_Id__c='yuuh3334';
       insert Client;
    Apexpages.Standardcontroller stdvice = new Apexpages.Standardcontroller(Client);
ClientSaveAndNew classobj= new ClientSaveAndNew (stdvice);
  
  classobj.saveAndNew();
   }
}