InternexDev_Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Personal Contact Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <label>Funding Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAN_TAN__c</fullName>
        <label>PAN/ TAN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>akritiv__Account_Key__c</fullName>
        <defaultValue>TEXT(0)</defaultValue>
        <externalId>true</externalId>
        <label>Account Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Applied_Monthly_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>Applied Monthly Interests</relationshipLabel>
        <relationshipName>Applied_Monthly_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commitment_fee_Accrued__c</fullName>
        <label>UL Fee Charged</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest Charged</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Interest Application</label>
        <referenceTo>Monthly_Interest_Application__c</referenceTo>
        <relationshipLabel>Applied Monthly Interests</relationshipLabel>
        <relationshipName>Applied_Monthly_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Applied Monthly Interest</label>
    <nameField>
        <label>Applied Monthly Interest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applied Monthly Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Client_Account__c.object
<CustomObject>
    <fields>
        <fullName>Borrowing_Base_Reserve__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Borrowing Base Reserve</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>Client__r.Name &amp;&apos;-&apos;&amp; Product__r.Name</formula>
        <inlineHelpText>Client Name &amp;&apos;-&apos;&amp; Product Name</inlineHelpText>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>akritiv__Brand__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commitment__c</fullName>
        <label>Min Utilization (%)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commitment_rate__c</fullName>
        <label>Unused Line Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Drawal_Fee_Percentage__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Drawal_Fee_Percentage__c</defaultValue>
        <label>Draw Fee Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Facility Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Index_Value__c</fullName>
        <label>Index Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <picklist>
            <picklistValues>
                <fullName>Citi Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internex base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LIBOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WS Prime</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>30 / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / ACTUAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Minimum_Drawal_Fee__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Minimum_Drawal_Fee__c</defaultValue>
        <label>Minimum Draw Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Origination_Fee__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Minimum_Origination_Fee__c</defaultValue>
        <label>Minimum Origination Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Origination_Fee_Percentage__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Origination_Fee_Percentage__c</defaultValue>
        <label>Origination Fee Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Payments__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Updated from payment Trigger</description>
        <label>Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spread__c</fullName>
        <label>Spread</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Client Account</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Client Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Daily_Interest_Accrual__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>CASESAFEID(Monthly_Interest_Application__r.Client_Account__c)</formula>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commitment__c</fullName>
        <label>Min Utilization (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commitment_rate__c</fullName>
        <label>Unused Line Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <label>Funding Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest__c</fullName>
        <formula>ROUND(( Prin_for_intt__c *  Interest_Rate_Applied__c*100 *(1/(No_of_Days__c* 100))),6)</formula>
        <label>Interest Accrued</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>30 / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / ACTUAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest_Application__c</fullName>
        <label>Monthly Interest Application</label>
        <referenceTo>Monthly_Interest_Application__c</referenceTo>
        <relationshipLabel>Daily Interest Accruals</relationshipLabel>
        <relationshipName>Daily_Interest_Accruals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Daily Interest Accrual</label>
    <nameField>
        <displayFormat>DI-{00000}</displayFormat>
        <label>Daily Interest Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Interest Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/FIU_Report__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>FIU Reports</relationshipLabel>
        <relationshipName>FIU_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <label>Funding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payments__c</fullName>
        <label>Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Name__c</fullName>
        <label>Transaction Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>FIU Report</label>
    <nameField>
        <displayFormat>FIUR-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FIU Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Monthly_Interest_Application__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>Monthly Interest Applications</relationshipLabel>
        <relationshipName>Monthly_Interest_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Start Month Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest Earned</label>
        <summarizedField>Daily_Interest_Accrual__c.Interest__c</summarizedField>
        <summaryFilterItems>
            <field>Daily_Interest_Accrual__c.Non_performing_asset__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Daily_Interest_Accrual__c.Monthly_Interest_Application__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Monthly Interest Application</label>
    <nameField>
        <displayFormat>MI-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Interest Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/TestConsolidatedGLReport.cls
@istest
public class TestConsolidatedGLReport {
	static testmethod void testmethod1()
    {
        Account TestAcc = new Account();
        TestAcc.Name ='Lockbox Account';
        TestAcc.AccountNumber = '00qsw';
        TestAcc.akritiv__Account_Key__c = 'key001' ;
        TestAcc.Funding_Limit__c = 100000;
        TestAcc.Email__c = 'abc@gmail.com';
        TestAcc.PAN_TAN__c = '123456789';
        TestAcc.BillingState = 'NY';
        TestAcc.BillingPostalCode = '99999';
        TestAcc.Funding_Limit__c = 100000;
        insert TestAcc;
        
        Account TestAcc1 = new Account();
        TestAcc1.Name ='abcd';
        TestAcc1.AccountNumber = '040qsw';
        TestAcc1.akritiv__Account_Key__c = 'key3001' ;
        TestAcc1.Funding_Limit__c = 500000;
        TestAcc1.Email__c = 'abcd@gmail.com';
        TestAcc1.PAN_TAN__c = '133456789';
        TestAcc1.BillingState = 'NY';
        TestAcc1.BillingPostalCode = '99999';
        TestAcc1.Funding_Limit__c = 300000;
        insert TestAcc1;
        
        
        Product__c testProduct = new Product__c();
        testProduct.Name = 'LOC';
        insert testProduct;
        
        akritiv__Brand__C TestClient = new akritiv__Brand__C();
        TestClient.CounterParty__c = TestAcc.Id;
        TestClient.Name = TestAcc.Name;
        insert TestClient;
        
        Client_Account__c testCA = new Client_Account__c();
        testCA.Client__c = TestClient.Id;
        testCA.Product__c = testProduct.Id;
        testCA.Funding_Limit__c = 100000;
        testCA.Commitment__c = 1000;
        testCA.Commitment_rate__c = 3.5;
        testCA.Index__c = 'WS Prime';
        testCA.Method__c = '360/Actual';
        testCA.Rate_Type__c = 'Fixed';
        testCA.Spread__c = 5;
        testCA.Rate__c = 10;
        testCA.Index_Value__c = 0;
        testCA.Borrowing_Base_Reserve__c = 0;
        testCA.Minimum_Drawal_Fee__c = 100;
        testCA.Minimum_Origination_Fee__c = 100;
        testCA.Drawal_Fee_Percentage__c = 8;
        testCA.Origination_Fee_Percentage__c = 6;
        insert testCA;

  		Monthly_Interest_Application__c MI = new Monthly_Interest_Application__c();
        MI.Client_Account__c =testCA.id;
       // MI.Name='abc';
        MI.Date__c = Date.today();
        Insert MI;
        
        Daily_Interest_Accrual__c DI = new Daily_Interest_Accrual__c();
        Di.Monthly_Interest_Application__c = MI.ID;
        DI.Date__c = Date.today();
        Insert DI;
        
        FIU_Report__c FIU = new FIU_Report__c();
        FIU.Client_Account__c = testCA.id;
        FIU.Date__c = Date.today();
        FIU.Funding__c = 1000;
        FIU.Payments__c = 10;
        FIU.Reference__c = 'Test1';
        FIU.Transaction_ID__c = 'Test1';
        FIU.Transaction_Name__c = 'Testing';
        insert FIU;
        
        Applied_Monthly_Interest__c AMI = new Applied_Monthly_Interest__c();
        AMI.Client_Account__c = testCA.id;
        //AMI.Client_Account__c = 'a1tR0000003PoUgIAK';
        AMI.Date__c = date.today();
        AMI.Monthly_Interest_Application__c = MI.Id;
        AMI.Commitment_fee_Accrued__c = -0.34;
        AMI.Reference__c = 'a1yR0000000tOalIAE';
        AMI.Name = '10-2016 Report';
        AMI.Interest__c= 2.38;
       // AMI.Monthly_Interest_Application__r.name = MI.Name;
        //AMI.CreatedDate = system.now();
        insert AMI;
        
        test.startTest();
        	Consolidated_GL_Report CG = new Consolidated_GL_Report();
            database.executeBatch(CG, 1);
        Test.stopTest();
    }       
       
        
    }