InternexDev_Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Personal Contact Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <label>Funding Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAN_TAN__c</fullName>
        <label>PAN/ TAN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>akritiv__Account_Key__c</fullName>
        <defaultValue>TEXT(0)</defaultValue>
        <externalId>true</externalId>
        <label>Account Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Client_Account__c.object
<CustomObject>
    <fields>
        <fullName>Borrowing_Base_Reserve__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Borrowing Base Reserve</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>Client__r.Name &amp;&apos;-&apos;&amp; Product__r.Name</formula>
        <inlineHelpText>Client Name &amp;&apos;-&apos;&amp; Product Name</inlineHelpText>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_External_Foreign_Key__c</fullName>
        <description>Created for mapping the Client account and</description>
        <externalId>true</externalId>
        <label>Client External Foreign Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>akritiv__Brand__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commitment__c</fullName>
        <label>Min Utilization (%)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commitment_rate__c</fullName>
        <label>Unused Line Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Drawal_Fee_Percentage__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Drawal_Fee_Percentage__c</defaultValue>
        <label>Draw Fee Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Facility Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IUF_Reserve_Retained__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IUF Reserve Retained</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Index_Value__c</fullName>
        <label>Index Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <picklist>
            <picklistValues>
                <fullName>Citi Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internex base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LIBOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WS Prime</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Due__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Interest Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>30 / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / ACTUAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Minimum_Drawal_Fee__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Minimum_Drawal_Fee__c</defaultValue>
        <label>Minimum Draw Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Origination_Fee__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Minimum_Origination_Fee__c</defaultValue>
        <label>Minimum Origination Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Non_performing_asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Accrual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origination_Fee_Percentage__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Origination_Fee_Percentage__c</defaultValue>
        <label>Origination Fee Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_External_ID__c</fullName>
        <label>Primary Contact External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_External_Foreign_Key__c</fullName>
        <externalId>true</externalId>
        <label>Product External Foreign Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Secondary_Contact_External_Id__c</fullName>
        <label>Secondary Contact External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spread__c</fullName>
        <label>Spread</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UL_Fee_Due__c</fullName>
        <defaultValue>0</defaultValue>
        <label>UL Fee Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Client Account</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Client Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Key__c</fullName>
        <externalId>true</externalId>
        <label>Contact Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/Test_trgonClientAccount.cls
@istest
public class Test_trgonClientAccount
{
    static id ank;
    static testmethod void trgonCA()
    {
        Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        Account TestAcc1 = new Account();
           TestAcc1.Name ='abcd';
           TestAcc1.AccountNumber = '040qsw';
           TestAcc1.akritiv__Account_Key__c = 'key3001' ;
           TestAcc1.Funding_Limit__c = 500000;
           TestAcc1.Email__c = 'abcd@gmail.com';
           TestAcc1.PAN_TAN__c = '133456789';
           TestAcc1.BillingState = 'NY';
           TestAcc1.BillingPostalCode = '99999';
           TestAcc1.Funding_Limit__c = 300000;
           insert TestAcc1;
        
        Contact  con = new Contact();
        con.CurrencyIsoCode ='USD';
        con.LastName='srivastava';
        con.AccountId=TestAcc.Id;
        con.Contact_Key__c='hgf5';
        con.Email ='ankima.sr@gmail.com';
        insert con;
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
         testProduct.External_Id__c='ghfhgf7';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
         TestClient.External_Id__c='hghh4';
          insert TestClient;
        
        
        
        Client_Account__c testCA = new Client_Account__c();
          ank = testCA.Id;
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
           testCA.Client_External_Foreign_Key__c ='hghh4';
           testCA.Product_External_Foreign_Key__c = 'ghfhgf7';
            testCA.Primary_Contact_External_ID__c='hgf5';
              testCA.Secondary_Contact_External_Id__c='ggg5';
        testCA.Non_performing_asset__c=true;
        testCA.IUF_Reserve_Retained__c=Null;
            insert testCA;
        testCA.Non_performing_asset__c=false;
        update testCA;
        
    }
    
     static id pank;
    static testmethod void trgonCA1()
    {
        Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        Account TestAcc1 = new Account();
           TestAcc1.Name ='abcd';
           TestAcc1.AccountNumber = '040qsw';
           TestAcc1.akritiv__Account_Key__c = 'key3001' ;
           TestAcc1.Funding_Limit__c = 500000;
           TestAcc1.Email__c = 'abcd@gmail.com';
           TestAcc1.PAN_TAN__c = '133456789';
           TestAcc1.BillingState = 'NY';
           TestAcc1.BillingPostalCode = '99999';
           TestAcc1.Funding_Limit__c = 300000;
           insert TestAcc1;
        
        Contact  con = new Contact();
        con.CurrencyIsoCode ='USD';
        con.LastName='srivastava';
        con.AccountId=TestAcc.Id;
        con.Contact_Key__c='ggg5';
        con.Email ='ankima.sr@gmail.com';
        insert con;
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
         testProduct.External_Id__c='ghfhgf7';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
         TestClient.External_Id__c='hghh4';
          insert TestClient;
        
        
        
        Client_Account__c testCA = new Client_Account__c();
          pank = testCA.Id;
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
           testCA.Client_External_Foreign_Key__c ='hghh4';
           testCA.Product_External_Foreign_Key__c = 'ghfhgf7';
            testCA.Primary_Contact_External_ID__c='hgf5';
              testCA.Secondary_Contact_External_Id__c='ggg5';
        testCA.Non_performing_asset__c=false;
        testCA.IUF_Reserve_Retained__c=Null;
        testCA.Interest_Due__c=100;
        testCA.UL_Fee_Due__c=100;
            insert testCA;
        testCA.Non_performing_asset__c=true;
        testCA.Interest_Due__c = 50;
        testCA.UL_Fee_Due__c=50;
        update testCA;
        
    }

    

}