InternexDev_Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Transaction_Date__c</fullName>
        <label>Business Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Personal Contact Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <label>Funding Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAN_TAN__c</fullName>
        <label>PAN/ TAN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>akritiv__Account_Key__c</fullName>
        <defaultValue>TEXT(0)</defaultValue>
        <externalId>true</externalId>
        <label>Account Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/BusinessTransactionDate__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Business_Transaction_Date__c</fullName>
        <label>Business Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Business Transaction Date</label>
</CustomObject>

InternexDev_Sandbox/src/objects/Client_Account__c.object
<CustomObject>
    <fields>
        <fullName>Borrowing_Base_Reserve__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Borrowing Base Reserve</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Transaction_Date__c</fullName>
        <label>Business Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>Client__r.Name &amp;&apos;-&apos;&amp; Product__r.Name</formula>
        <inlineHelpText>Client Name &amp;&apos;-&apos;&amp; Product Name</inlineHelpText>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>akritiv__Brand__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commitment__c</fullName>
        <label>Min Utilization (%)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commitment_rate__c</fullName>
        <label>Unused Line Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Drawal_Fee_Percentage__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Drawal_Fee_Percentage__c</defaultValue>
        <label>Draw Fee Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FIU_Outstanding__c</fullName>
        <formula>(Sum_of_Received_funds__c - (Sum_of_Payments__c - ((Sum_of_IUF_Retained__c + Sum_of_Interest_Recovered__c + Sum_of_UL_Fee_Recovered__c + Sum_of_Fee__c))))- Payments__c - Sum_of_Manually_Created_IUF_Retained__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula : (Sum of Received funds - (Sum of Applied Payments - (Sum of IUF Retained + Interest Recovered + UL Fee Due Recovered + Fee)))</inlineHelpText>
        <label>Principal Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Facility Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IUF_Reserve_Retained__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IUF Reserve Retained</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Index_Value__c</fullName>
        <label>Index Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <picklist>
            <picklistValues>
                <fullName>Citi Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internex base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LIBOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WS Prime</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Due_Since__c</fullName>
        <label>Interest Due Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_Due__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Interest Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>30 / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / ACTUAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Minimum_Drawal_Fee__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Minimum_Drawal_Fee__c</defaultValue>
        <label>Minimum Draw Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Origination_Fee__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Minimum_Origination_Fee__c</defaultValue>
        <label>Minimum Origination Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Non_performing_asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Accrual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origination_Fee_Percentage__c</fullName>
        <defaultValue>$Setup.Internex_Fees__c.Origination_Fee_Percentage__c</defaultValue>
        <label>Origination Fee Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spread__c</fullName>
        <label>Spread</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UL_Fee_Due_Since__c</fullName>
        <label>UL Fee Due Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UL_Fee_Due__c</fullName>
        <defaultValue>0</defaultValue>
        <label>UL Fee Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Client Account</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Client Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Daily_Interest_Accrual__c.object
<CustomObject>
    <fields>
        <fullName>Applied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Applied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Transaction_Date__c</fullName>
        <label>Business Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>CASESAFEID(Monthly_Interest_Application__r.Client_Account__c)</formula>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commitment__c</fullName>
        <label>Min Utilization (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commitment_rate__c</fullName>
        <label>Unused Line Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FIU_Outstanding__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <label>Funding Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest_Base_Rate__c</fullName>
        <label>Interest Base Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Interest_Spread__c</fullName>
        <label>Interest Spread</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>30 / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / ACTUAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest_Application__c</fullName>
        <label>Monthly Interest Application</label>
        <referenceTo>Monthly_Interest_Application__c</referenceTo>
        <relationshipLabel>Daily Interest Accruals</relationshipLabel>
        <relationshipName>Daily_Interest_Accruals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Daily Interest Accrual</label>
    <nameField>
        <displayFormat>DI-{00000}</displayFormat>
        <label>Daily Interest Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Interest Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Monthly_Interest_Application__c.object
<CustomObject>
    <fields>
        <fullName>Applied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Applied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Transaction_Date__c</fullName>
        <label>Business Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>Monthly Interest Applications</relationshipLabel>
        <relationshipName>Monthly_Interest_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Start Month Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_Base_Rate__c</fullName>
        <label>Interest Base Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Interest_Charged__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Interest Charged</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Spread__c</fullName>
        <label>Interest Spread</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UL_Fee_Charged__c</fullName>
        <defaultValue>0</defaultValue>
        <label>UL Fee Charged</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Monthly Interest Application</label>
    <nameField>
        <displayFormat>MI-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Interest Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Business_Transaction_Date__c</fullName>
        <label>Business Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/Test_trgonDailyInterestAccrual.cls
@istest
public class Test_trgonDailyInterestAccrual 
{
    static testmethod void trgonDailyInterestAcc()
    {
        BusinessTransactionDate__c BTD = new BusinessTransactionDate__c();
        BTD.Business_Transaction_Date__c = Date.today();
        insert BTD;

      
        
        Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        Account TestAcc1 = new Account();
           TestAcc1.Name ='abcd';
           TestAcc1.AccountNumber = '040qsw';
           TestAcc1.akritiv__Account_Key__c = 'key3001' ;
           TestAcc1.Funding_Limit__c = 500000;
           TestAcc1.Email__c = 'abcd@gmail.com';
           TestAcc1.PAN_TAN__c = '133456789';
           TestAcc1.BillingState = 'NY';
           TestAcc1.BillingPostalCode = '99999';
           TestAcc1.Funding_Limit__c = 300000;
           insert TestAcc1;
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
          insert TestClient;
        
         Client_Account__c testCA = new Client_Account__c();
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
        testCA.IUF_Reserve_Retained__c=20;
        testCA.Interest_Due__c=100;
        testCA.UL_Fee_Due__c=10;
        testCA.Interest_Due_Since__c=date.today();
        testCA.UL_Fee_Due_Since__c=date.today();
            insert testCA;


        Monthly_Interest_Application__c MIA = new Monthly_Interest_Application__c();
        MIA.Client_Account__c = testCA.Id;
        MIA.Date__c=date.today();
        MIA.CurrencyIsoCode='USD';
        MIA.Applied__c = True;
        MIA.Interest_Charged__c=2;
        MIA.UL_Fee_Charged__c = 2;
        insert MIA;
        
        Daily_Interest_Accrual__c DIA = new Daily_Interest_Accrual__c();
        DIA.Monthly_Interest_Application__c = MIA.Id;
        DIA.Business_Transaction_Date__c = date.today()+27;
        DIA.Date__c=date.today()+27;
        DIA.Interest_Base_Rate__c = 2;
        DIA.Interest_Spread__c=2;
        DIA.CurrencyIsoCode = 'USD';
        DIA.FIU_Outstanding__c=200;
        DIA.Funding_Limit__c=500;
        DIA.Commitment__c=20;
        DIA.Method__c='ACTUAL/360';
        DIA.Non_performing_asset__c=false;
        DIA.Commitment_rate__c =1000;
       
        insert DIA;
        
        
    }
    static testmethod void trgonDailyInterestAcc1()
    {
        BusinessTransactionDate__c BTD = new BusinessTransactionDate__c();
        BTD.Business_Transaction_Date__c = Date.today();
        insert BTD;

      
        
        Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        Account TestAcc1 = new Account();
           TestAcc1.Name ='abcd';
           TestAcc1.AccountNumber = '040qsw';
           TestAcc1.akritiv__Account_Key__c = 'key3001' ;
           TestAcc1.Funding_Limit__c = 500000;
           TestAcc1.Email__c = 'abcd@gmail.com';
           TestAcc1.PAN_TAN__c = '133456789';
           TestAcc1.BillingState = 'NY';
           TestAcc1.BillingPostalCode = '99999';
           TestAcc1.Funding_Limit__c = 300000;
           insert TestAcc1;
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
          insert TestClient;
        
         Client_Account__c testCA = new Client_Account__c();
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
        testCA.IUF_Reserve_Retained__c=6;
        testCA.Interest_Due__c=100;
        testCA.UL_Fee_Due__c=10;
        testCA.Interest_Due_Since__c=date.today();
        testCA.UL_Fee_Due_Since__c=null;
            insert testCA;


        Monthly_Interest_Application__c MIA = new Monthly_Interest_Application__c();
        MIA.Client_Account__c = testCA.Id;
        MIA.Date__c=date.today();
        MIA.CurrencyIsoCode='USD';
        MIA.Applied__c = True;
        MIA.Interest_Charged__c=2;
        MIA.UL_Fee_Charged__c = 2;
        insert MIA;
        
        Daily_Interest_Accrual__c DIA = new Daily_Interest_Accrual__c();
        DIA.Monthly_Interest_Application__c = MIA.Id;
        DIA.Business_Transaction_Date__c = date.today()+27;
        DIA.Date__c=date.today()+27;
        DIA.Interest_Base_Rate__c = 2;
        DIA.Interest_Spread__c=2;
        DIA.CurrencyIsoCode = 'USD';
        DIA.FIU_Outstanding__c=200;
        DIA.Funding_Limit__c=500;
        DIA.Commitment__c=20;
        DIA.Method__c='ACTUAL/360';
        DIA.Non_performing_asset__c=false;
        DIA.Commitment_rate__c =1000;
       
        insert DIA;
        
        
    }
    static testmethod void trgonDailyInterestAcc2()
    {
        BusinessTransactionDate__c BTD = new BusinessTransactionDate__c();
        BTD.Business_Transaction_Date__c = Date.today();
        insert BTD;

      
        
        Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        Account TestAcc1 = new Account();
           TestAcc1.Name ='abcd';
           TestAcc1.AccountNumber = '040qsw';
           TestAcc1.akritiv__Account_Key__c = 'key3001' ;
           TestAcc1.Funding_Limit__c = 500000;
           TestAcc1.Email__c = 'abcd@gmail.com';
           TestAcc1.PAN_TAN__c = '133456789';
           TestAcc1.BillingState = 'NY';
           TestAcc1.BillingPostalCode = '99999';
           TestAcc1.Funding_Limit__c = 300000;
           insert TestAcc1;
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
          insert TestClient;
        
         Client_Account__c testCA = new Client_Account__c();
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
        testCA.IUF_Reserve_Retained__c=0;
        testCA.Interest_Due__c=100;
        testCA.UL_Fee_Due__c=10;
        testCA.Interest_Due_Since__c=date.today();
        testCA.UL_Fee_Due_Since__c=null;
            insert testCA;


        Monthly_Interest_Application__c MIA = new Monthly_Interest_Application__c();
        MIA.Client_Account__c = testCA.Id;
        MIA.Date__c=date.today();
        MIA.CurrencyIsoCode='USD';
        MIA.Applied__c = True;
        MIA.Interest_Charged__c=2;
        MIA.UL_Fee_Charged__c = 2;
        insert MIA;
        
        Daily_Interest_Accrual__c DIA = new Daily_Interest_Accrual__c();
        DIA.Monthly_Interest_Application__c = MIA.Id;
        DIA.Business_Transaction_Date__c = date.today()+27;
        DIA.Date__c=date.today()+27;
        DIA.Interest_Base_Rate__c = 2;
        DIA.Interest_Spread__c=2;
        DIA.CurrencyIsoCode = 'USD';
        DIA.FIU_Outstanding__c=200;
        DIA.Funding_Limit__c=500;
        DIA.Commitment__c=20;
        DIA.Method__c='ACTUAL/360';
        DIA.Non_performing_asset__c=false;
        DIA.Commitment_rate__c =1000;
       
        insert DIA;
        
        
    }
    
     static testmethod void trgonDailyInterestAcc3()
    {
        BusinessTransactionDate__c BTD = new BusinessTransactionDate__c();
        BTD.Business_Transaction_Date__c = Date.today();
        insert BTD;

      
        
        Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        Account TestAcc1 = new Account();
           TestAcc1.Name ='abcd';
           TestAcc1.AccountNumber = '040qsw';
           TestAcc1.akritiv__Account_Key__c = 'key3001' ;
           TestAcc1.Funding_Limit__c = 500000;
           TestAcc1.Email__c = 'abcd@gmail.com';
           TestAcc1.PAN_TAN__c = '133456789';
           TestAcc1.BillingState = 'NY';
           TestAcc1.BillingPostalCode = '99999';
           TestAcc1.Funding_Limit__c = 300000;
           insert TestAcc1;
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
          insert TestClient;
        
         Client_Account__c testCA = new Client_Account__c();
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
        testCA.IUF_Reserve_Retained__c=0.01;
        testCA.Interest_Due__c=100;
        testCA.UL_Fee_Due__c=10;
        testCA.Interest_Due_Since__c=null;
        testCA.UL_Fee_Due_Since__c=date.today();
            insert testCA;


        Monthly_Interest_Application__c MIA = new Monthly_Interest_Application__c();
        MIA.Client_Account__c = testCA.Id;
        MIA.Date__c=date.today();
        MIA.CurrencyIsoCode='USD';
        MIA.Applied__c = True;
        MIA.Interest_Charged__c=2;
        MIA.UL_Fee_Charged__c = 2;
        insert MIA;
        
        Daily_Interest_Accrual__c DIA = new Daily_Interest_Accrual__c();
        DIA.Monthly_Interest_Application__c = MIA.Id;
        DIA.Business_Transaction_Date__c = date.today()+27;
        DIA.Date__c=date.today()+27;
        DIA.Interest_Base_Rate__c = 2;
        DIA.Interest_Spread__c=2;
        DIA.CurrencyIsoCode = 'USD';
        DIA.FIU_Outstanding__c=200;
        DIA.Funding_Limit__c=500;
        DIA.Commitment__c=20;
        DIA.Method__c='ACTUAL/360';
        DIA.Non_performing_asset__c=false;
        DIA.Commitment_rate__c =1000;
       
        insert DIA;
        
        
    }
    // -----------------to make BsnsTransact = null (satisfying if condition) START------------
    
    static testmethod void trgonDailyInterestAcc4()
    {
       /* BusinessTransactionDate__c BTD = new BusinessTransactionDate__c();
        BTD.Business_Transaction_Date__c = Date.today();
        insert BTD; */

      
        
        Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        Account TestAcc1 = new Account();
           TestAcc1.Name ='abcd';
           TestAcc1.AccountNumber = '040qsw';
           TestAcc1.akritiv__Account_Key__c = 'key3001' ;
           TestAcc1.Funding_Limit__c = 500000;
           TestAcc1.Email__c = 'abcd@gmail.com';
           TestAcc1.PAN_TAN__c = '133456789';
           TestAcc1.BillingState = 'NY';
           TestAcc1.BillingPostalCode = '99999';
           TestAcc1.Funding_Limit__c = 300000;
           insert TestAcc1;
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
          insert TestClient;
        
         Client_Account__c testCA = new Client_Account__c();
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
        testCA.IUF_Reserve_Retained__c=0.01;
        testCA.Interest_Due__c=100;
        testCA.UL_Fee_Due__c=10;
        testCA.Interest_Due_Since__c=null;
        testCA.UL_Fee_Due_Since__c=date.today();
            insert testCA;


        Monthly_Interest_Application__c MIA = new Monthly_Interest_Application__c();
        MIA.Client_Account__c = testCA.Id;
        MIA.Date__c=date.today();
        MIA.CurrencyIsoCode='USD';
        MIA.Applied__c = True;
        MIA.Interest_Charged__c=2;
        MIA.UL_Fee_Charged__c = 2;
        insert MIA;
        
        Daily_Interest_Accrual__c DIA = new Daily_Interest_Accrual__c();
        DIA.Monthly_Interest_Application__c = MIA.Id;
       // DIA.Business_Transaction_Date__c = date.today()+27;
        DIA.Date__c=date.today()+27;
        DIA.Interest_Base_Rate__c = 2;
        DIA.Interest_Spread__c=2;
        DIA.CurrencyIsoCode = 'USD';
        DIA.FIU_Outstanding__c=200;
        DIA.Funding_Limit__c=500;
        DIA.Commitment__c=20;
        DIA.Method__c='ACTUAL/360';
        DIA.Non_performing_asset__c=false;
        DIA.Commitment_rate__c =1000;
       
        insert DIA;
        
        
    }

 // -----------------to make BsnsTransact = null (satisfying if condition) END------------------)


static testmethod void trgonDailyInterestAcc5()
    {
        BusinessTransactionDate__c BTD = new BusinessTransactionDate__c();
        BTD.Business_Transaction_Date__c = Date.today();
        insert BTD;

      
        
        Account TestAcc = new Account();
           TestAcc.Name ='abc';
           TestAcc.AccountNumber = '00qsw';
           TestAcc.akritiv__Account_Key__c = 'key001' ;
           TestAcc.Funding_Limit__c = 100000;
           TestAcc.Email__c = 'abc@gmail.com';
           TestAcc.PAN_TAN__c = '123456789';
           TestAcc.BillingState = 'NY';
           TestAcc.BillingPostalCode = '99999';
           TestAcc.Funding_Limit__c = 100000;
           insert TestAcc;
        
        Account TestAcc1 = new Account();
           TestAcc1.Name ='abcd';
           TestAcc1.AccountNumber = '040qsw';
           TestAcc1.akritiv__Account_Key__c = 'key3001' ;
           TestAcc1.Funding_Limit__c = 500000;
           TestAcc1.Email__c = 'abcd@gmail.com';
           TestAcc1.PAN_TAN__c = '133456789';
           TestAcc1.BillingState = 'NY';
           TestAcc1.BillingPostalCode = '99999';
           TestAcc1.Funding_Limit__c = 300000;
           insert TestAcc1;
        
          Product__c testProduct = new Product__c();
          testProduct.Name = 'LOC';
          insert testProduct;
        
          akritiv__Brand__C TestClient = new akritiv__Brand__C();
         TestClient.CounterParty__c = TestAcc.Id;
         TestClient.Name = TestAcc.Name;
          insert TestClient;
        
         Client_Account__c testCA = new Client_Account__c();
           testCA.Client__c = TestClient.Id;
           testCA.Product__c = testProduct.Id;
           testCA.Funding_Limit__c = 100000;
           testCA.Commitment__c = 1000;
           testCA.Commitment_rate__c = 3.5;
           testCA.Index__c = 'WS Prime';
           testCA.Method__c = '360/Actual';
           testCA.Rate_Type__c = 'Fixed';
           testCA.Spread__c = 5;
            testCA.Rate__c = 10;
            testCA.Index_Value__c = 0;
            testCA.Borrowing_Base_Reserve__c = 0;
            testCA.Minimum_Drawal_Fee__c = 100;
            testCA.Minimum_Origination_Fee__c = 100;
            testCA.Drawal_Fee_Percentage__c = 8;
            testCA.Origination_Fee_Percentage__c = 6;
        testCA.IUF_Reserve_Retained__c=6;
        testCA.Interest_Due__c=100;
        testCA.UL_Fee_Due__c=10;
        testCA.Interest_Due_Since__c=null;
        testCA.UL_Fee_Due_Since__c=date.today();
            insert testCA;


        Monthly_Interest_Application__c MIA = new Monthly_Interest_Application__c();
        MIA.Client_Account__c = testCA.Id;
        MIA.Date__c=date.today();
        MIA.CurrencyIsoCode='USD';
        MIA.Applied__c = True;
        MIA.Interest_Charged__c=2;
        MIA.UL_Fee_Charged__c = 2;
        insert MIA;
        
        Daily_Interest_Accrual__c DIA = new Daily_Interest_Accrual__c();
        DIA.Monthly_Interest_Application__c = MIA.Id;
        DIA.Business_Transaction_Date__c = date.today()+27;
        DIA.Date__c=date.today()+27;
        DIA.Interest_Base_Rate__c = 2;
        DIA.Interest_Spread__c=2;
        DIA.CurrencyIsoCode = 'USD';
        DIA.FIU_Outstanding__c=200;
        DIA.Funding_Limit__c=500;
        DIA.Commitment__c=20;
        DIA.Method__c='ACTUAL/360';
        DIA.Non_performing_asset__c=false;
        DIA.Commitment_rate__c =1000;
       
        insert DIA;
        delete DIA;
        
        
    }



}