InternexDev_Sandbox/src/objects/Applied_Monthly_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>Applied Monthly Interests</relationshipLabel>
        <relationshipName>Applied_Monthly_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commitment_fee_Accrued__c</fullName>
        <label>UL Fee Charged</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest Charged</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Interest Application</label>
        <referenceTo>Monthly_Interest_Application__c</referenceTo>
        <relationshipLabel>Applied Monthly Interests</relationshipLabel>
        <relationshipName>Applied_Monthly_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Applied Monthly Interest</label>
    <nameField>
        <label>Applied Monthly Interest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applied Monthly Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Client_Account__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>Client__r.Name &amp;&apos;-&apos;&amp; Product__r.Name</formula>
        <inlineHelpText>Client Name &amp;&apos;-&apos;&amp; Product Name</inlineHelpText>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commitment__c</fullName>
        <label>Min Utilization (%)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commitment_rate__c</fullName>
        <label>Unused Line Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Eligible_For_Funding__c</fullName>
        <description>Sum of All debtors Eligible for Funding ,Updated from Debtor Trigger</description>
        <label>Eligible For Funding1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FIU_Outstanding__c</fullName>
        <formula>(Sum_of_Received_funds__c - (Sum_of_Payments__c - ((Sum_of_IUF_Retained__c + Sum_of_Interest_Recovered__c + Sum_of_UL_Fee_Recovered__c + Sum_of_Fee__c))))- Payments__c - Sum_of_Manually_Created_IUF_Retained__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula : (Sum of Received funds - (Sum of Applied Payments - (Sum of IUF Retained + Interest Recovered + UL Fee Due Recovered + Fee)))</inlineHelpText>
        <label>Principal Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funding_Limit__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Data Source: Grade or Portal</inlineHelpText>
        <label>Facility Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Availability__c</fullName>
        <label>Gross Availability1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <picklist>
            <picklistValues>
                <fullName>Citi Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internex base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LIBOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WS Prime</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ineligibles_Amount__c</fullName>
        <description>Updated Sum of Ineligibles of related Debtor from Debtor trigger.</description>
        <label>Ineligibles</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <summarizedField>Debtor__c.Invoice_Amount__c</summarizedField>
        <summaryForeignKey>Debtor__c.Client_Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>30 / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTUAL / ACTUAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MinCommitmentAmount__c</fullName>
        <formula>Funding_Limit__c  * (Commitment__c)</formula>
        <inlineHelpText>Min Utilization (%) * Client Funding Limit</inlineHelpText>
        <label>Min Utilization Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Availability__c</fullName>
        <formula>Borrowing_Base__c - FIU_Outstanding__c</formula>
        <inlineHelpText>Formula : Borrowing Base - Principal Balance</inlineHelpText>
        <label>Net Availability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Non_performing_asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Accrual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payments__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Updated from payment Trigger</description>
        <label>Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spread__c</fullName>
        <label>Spread</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sum_of_Net_Availability__c</fullName>
        <description>Showing the Gross Availability in Pageblock Table</description>
        <formula>Gross_Availability__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Gross_Availability</inlineHelpText>
        <label>Gross Availability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Client Account</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Client Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Consolidated_GL_Report__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>Consolidated GL Reports</relationshipLabel>
        <relationshipName>Consolidated_GL_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Currency__c</fullName>
        <label>Funding (Currency)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <label>Funding</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payments_Currency__c</fullName>
        <label>Payments(Currency)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payments__c</fullName>
        <label>Payments</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Name__c</fullName>
        <label>Transaction Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Consolidated GL Report</label>
    <nameField>
        <displayFormat>CGL-{000000}</displayFormat>
        <label>Consolidated GL Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consolidated GL Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/FIU_Report__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>FIU Reports</relationshipLabel>
        <relationshipName>FIU_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closing_FIU_Balance__c</fullName>
        <label>Closing FIU Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <label>Funding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opening_FIU_Balance__c</fullName>
        <label>Opening FIU Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payments__c</fullName>
        <label>Payments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Name__c</fullName>
        <label>Transaction Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>FIU Report</label>
    <nameField>
        <displayFormat>FIUR-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FIU Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Monthly_Interest_Application__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>Monthly Interest Applications</relationshipLabel>
        <relationshipName>Monthly_Interest_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Start Month Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest Earned</label>
        <summarizedField>Daily_Interest_Accrual__c.Interest__c</summarizedField>
        <summaryFilterItems>
            <field>Daily_Interest_Accrual__c.Non_performing_asset__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Daily_Interest_Accrual__c.Monthly_Interest_Application__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>MinCommitmentAmount__c</fullName>
        <formula>Client_Account__r.MinCommitmentAmount__c</formula>
        <label>Min Utilization Amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Interest Application</label>
    <nameField>
        <displayFormat>MI-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Interest Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/Consolidated_GL_Report.cls
global class Consolidated_GL_Report implements Database.Batchable<sobject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'Select id,FIU_Outstanding__c,Non_performing_asset__c,Commitment__c,Commitment_rate__c,Funding_Limit__c,MinCommitmentAmount__c,';
        query = query+'Invoice_Amount__c,Sum_of_Net_Availability__c,Ineligibles_Amount__c,Eligible_For_Funding__c,Gross_Availability__c,Net_Availability__c,Index__c,Rate__c,Rate_Type__c,Method__c,Spread__c from Client_Account__c Limit 49999 '; //where id = \''+'a0Y61000001e6hs'+'\'
        system.debug('==>query '+ query);
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Client_Account__c> scope) {
        set<string> ClientAccountIDs = new Set<string>();
        for(Client_Account__c CA : scope)
        {
            ClientAccountIDs.add(CA.Id);
        }
        Delete[Select id from Consolidated_GL_Report__c where Client_Account__c in : scope and createddate >: system.now()-1];
        CreatepaymentandfundingRequestinfo(ClientAccountIDs);
        Createinterestinfo(ClientAccountIDs);
    }
    global void finish(Database.BatchableContext BC)
    {
        InvoiceAgingCalculations IAC = new InvoiceAgingCalculations();
        Database.executeBatch(IAC, 1);
    }
    public void CreatepaymentandfundingRequestinfo(Set<string> scope)
    {
        system.debug('scope====> '+scope);
        system.debug('CreatepaymentandfundingRequestinfo====> ');
        List<Consolidated_GL_Report__c> CGL_list = new List<Consolidated_GL_Report__c>();
        List<FIU_Report__c> FIUreport_list = [Select id,Transaction_Name__c,Transaction_ID__c,Date__c,Payments__c,Reference__c,
                                              Client_Account__c,Opening_FIU_Balance__c,Closing_FIU_Balance__c,Funding__c
                                              from FIU_Report__c where Client_Account__c in : scope and createddate >: system.now()-1];
        system.debug('FIUreport_list size====> '+ FIUreport_list.size());
        for(FIU_Report__c FIU : FIUreport_list)
        {
            Consolidated_GL_Report__c CGL = new Consolidated_GL_Report__c();
            CGL.Client_Account__c = FIU.Client_Account__c;
            CGL.Date__c = FIU.Date__c;
            CGL.Funding__c = FIU.Funding__c;
            CGL.Funding_currency__c = FIU.Funding__c;
            CGL.Payments__c = FIU.Payments__c;
            CGL.Payments_Currency__c = FIU.Payments__c;
            CGL.Reference__c = FIU.Reference__c;
            CGL.Transaction_ID__c = FIU.Transaction_ID__c;
            CGL.Transaction_Name__c = FIU.Transaction_Name__c;
            CGL_list.add(CGL);
        }
        try
        {
            insert CGL_list;
        }catch(exception e){system.debug('exception  '+ e);}
    }
    Public Void Createinterestinfo(Set<string> scope)
    {
        system.debug('scope====> '+scope);
        system.debug('Createinterestinfo====> ');
        List<Consolidated_GL_Report__c> CGL_list = new List<Consolidated_GL_Report__c>();
        list<Applied_Monthly_Interest__c> MonthlyInterest_List = [Select id,Name,Client_Account__c,Date__c,Commitment_fee_Accrued__c,Interest__c,Monthly_Interest_Application__c,Monthly_Interest_Application__r.name,
                                                                 Reference__c from Applied_Monthly_Interest__c where Client_Account__c in : scope and createddate >: system.now()-1];
    	 system.debug('MonthlyInterest_List====> '+ MonthlyInterest_List.size());
        for(Applied_Monthly_Interest__c AMI : MonthlyInterest_List)
        {
            Consolidated_GL_Report__c CGL = new Consolidated_GL_Report__c();
            CGL.Client_Account__c = AMI.Client_Account__c;
            CGL.Date__c =AMI.Date__c;
            CGL.Funding__c = AMI.Commitment_fee_Accrued__c + AMI.Interest__c;
            CGL.Funding_currency__c = AMI.Commitment_fee_Accrued__c + AMI.Interest__c;
           // CGL.Payments__c = 0;
           // CGL.Payments_Currency__c = FIU.Payments__c;
            CGL.Reference__c = AMI.Reference__c;
            CGL.Transaction_ID__c = AMI.Monthly_Interest_Application__r.name;
            CGL.Transaction_Name__c = AMI.Name.replace('Report','Interest');
            CGL_list.add(CGL); 
        }
        try
        {
            insert CGL_list;
        }catch(exception e){system.debug('exception  '+ e);}
    }
}