InternexDev_Sandbox/src/objects/Client_Account__c.object
<CustomObject>
    <fields>
        <fullName>AP_16_30__c</fullName>
        <defaultValue>0</defaultValue>
        <label>16-30</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AP_1_15__c</fullName>
        <defaultValue>0</defaultValue>
        <label>1-15</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AP_31_60__c</fullName>
        <defaultValue>0</defaultValue>
        <label>31-60</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AP_61_90__c</fullName>
        <defaultValue>0</defaultValue>
        <label>61-90</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AP_90__c</fullName>
        <defaultValue>0</defaultValue>
        <label>90+</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AP_Current__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>Client__r.Name &amp;&apos;-&apos;&amp; Product__r.Name</formula>
        <inlineHelpText>Client Name &amp;&apos;-&apos;&amp; Product Name</inlineHelpText>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>akritiv__Brand__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Net_Availability__c</fullName>
        <formula>Borrowing_Base__c - FIU_Outstanding__c</formula>
        <inlineHelpText>Formula : Borrowing Base - Principal Balance</inlineHelpText>
        <label>Net Availability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Client__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Client Account</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Client Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Debtor__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>Debtors</relationshipLabel>
        <relationshipName>Debtors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client_Product_Counterparty__c</fullName>
        <formula>Client_Account__r.Client_Account__c &amp; &apos;-&apos; &amp; Counterparty__r.Name</formula>
        <label>Client Product Counterparty</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contra_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Contra Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debtor_Adjusted_AR__c</fullName>
        <formula>Eligible_For_Funding__c -(ROUND(IF(Actual_Debtor_Concentration__c &gt; Concentration_Limit__c,((Actual_Debtor_Concentration__c - Concentration_Limit__c)*Client_Account__r.Eligible_For_Funding_formula__c),0),5))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula: Eligible AR - Excess Concentration</inlineHelpText>
        <label>Debtor Adjusted AR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debtor_Net_Eligible_AR__c</fullName>
        <formula>MIN(Debtor_Adjusted_AR__c,Eligible_AR__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula: Minimum(Debtor Adjusted AR, Eligible AR Limit)</inlineHelpText>
        <label>Debtor Net Eligible AR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Availability__c</fullName>
        <formula>IF((Debtor_Net_Eligible_AR__c*Advance_Rate__c)-Borrowing_Base_Reserve__c &lt; 0,0,(Debtor_Net_Eligible_AR__c*Advance_Rate__c)-Borrowing_Base_Reserve__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula: (Debtor Net Eligible AR*(Advance Rate/100))-Borrowing Base Reserve</inlineHelpText>
        <label>Net Availability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Debtor</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Debtor Account</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debtor Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/AccountPayableEntry.cls
public with sharing class AccountPayableEntry {

    public PageReference deb_Save() {
        try{
           list<debtor__c> DebtorUpdate_list = new list<Debtor__c>();
           for(Debtorwrap DW: Debtorwraplist)
           {
                if(DW.check == True)
                {
                    DebtorUpdate_list.add(DW.Debtor);
                }           
           }
           Update DebtorUpdate_list;
           DebtorUpdate_list.clear();
           search();
        }
        catch(Exception e){
        system.debug('Exception --> '+ e);
        apexpages.addmessage(new ApexPages.message(ApexPages.severity.Error,String.valueof(e.getMessage())));}
        return null;
    }


    public PageReference CA_Save() {
          try{
            update CA;
        }
        catch(Exception e){
        system.debug('Exception --> '+ e);
        apexpages.addmessage(new ApexPages.message(ApexPages.severity.Error,String.valueof(e.getMessage())));}
        return null;
    }


public boolean showSection { get; set; }
Public akritiv__Transaction__c Invoice{ get; set; }
Public client_account__C CA{ get; set; }
Public List<Debtorwrap> Debtorwraplist { get; set; }

    public AccountPayableEntry()
    {
         CA = new client_account__C();
         Invoice = new akritiv__Transaction__c();
         showSection = false;
         Debtorwraplist = new List<Debtorwrap>();
    }

    public PageReference search() {
        system.debug('Client-Account -> '+ Invoice.Client_Acc__c);
    
        if(Invoice.Client_Acc__c != NULL)
        {
                CA = [Select id,Name,Status__c,Client_Account__c,Client__c,Product__c,AP_Current__c,AP_31_60__c,AP_1_15__c,AP_61_90__c,AP_16_30__c,AP_90__c from client_account__C where Id =: Invoice.Client_Acc__c];
                showSection = true;
                List<DebtorWrap> list_Debtorwrap = new List<DebtorWrap>();
                integer count = 0;
                for(Debtor__c deb: [Select id,Name,Contra_Balance__c,Client_Account__c,Client_Product_Counterparty__c,Net_Availability__c,Debtor_Net_Eligible_AR__c,Debtor_Adjusted_AR__c from Debtor__c where Client_Account__c =: Invoice.Client_Acc__c])
                {
                    DebtorWrap debwrp = new DebtorWrap(false,deb,count);
                    list_Debtorwrap.add(debwrp);
                    count++;
                }
                system.debug('Debtorwraplist--> '+ list_Debtorwrap);
                Debtorwraplist = list_Debtorwrap;
        }
        return null;
    }

public class DebtorWrap
{
    public boolean check {get;set;}
    public Debtor__c debtor{get;set;}
    Public integer rowCount{get;set;}
    public DebtorWrap(Boolean chk, Debtor__c deb,integer c)
    {
        check = chk;
        Debtor = deb;
        rowCount = c; 
    }
}

}