InternexDev_Sandbox/src/objects/Client_Account__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>Client__r.Name &amp;&apos;-&apos;&amp; Product__r.Name</formula>
        <inlineHelpText>Client Name &amp;&apos;-&apos;&amp; Product Name</inlineHelpText>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Portal_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Client Account</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Client Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Debtor__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Client_Account__c</referenceTo>
        <relationshipLabel>Debtors</relationshipLabel>
        <relationshipName>Debtors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DBA_Count_for_Grade__c</fullName>
        <defaultValue>0</defaultValue>
        <label>DBA Count for Grade</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DBA_Count_for_Portal__c</fullName>
        <defaultValue>0</defaultValue>
        <label>DBA Count for Portal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Portal_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Debtor</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Debtor Account</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debtor Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/DBAName_Batch.cls
global class DBAName_Batch implements Database.Batchable<Sobject>,Database.Allowscallouts{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        string query = 'SELECT Id, Name, DBA_Count_for_Grade__c, CreatedDate,DBA_Count_for_Portal__c,External_Id__c,Portal_External_Id__c,';
               query = query+'Client_Account__c FROM Debtor__c where ((External_Id__c != NULL and DBA_Count_for_Grade__c > 0) or (Portal_External_Id__c != NULL and DBA_Count_for_Portal__c > 0)) limit 49999';
        system.debug('Query ==> '+ query);
        return Database.getQueryLocator(query);
    }
    global Void Execute(Database.BatchableContext BC,list<Debtor__c> Scope)
    {
        for(Debtor__c Deb : Scope)
        {
            if(Deb.External_Id__c != NULL && Deb.DBA_Count_for_Grade__c > 0)
                TPSSF.TPConnectorService.SubmitExt('Debtor__c',Deb.Id,'','','sendtogradedba','akritiv-inernex-dba-name','',UserInfo.getUserId(),UserInfo.getSessionId(),'PartnerUrl', UserInfo.getUserName(),'','','');
            if(Deb.Portal_External_Id__c != NULL && Deb.DBA_Count_for_Portal__c > 0)
                TPSSF.TPConnectorService.SubmitExt('Debtor__c',Deb.Id,'','','sendtoportaldba','akritiv-inernex-dba-name','',UserInfo.getUserId(),UserInfo.getSessionId(),'PartnerUrl', UserInfo.getUserName(),'','','');
        }
    }
    global void Finish(Database.BatchableContext BC)
    {
        
    }
}