InternexDev_Sandbox/src/objects/Client_Account__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <formula>Client__r.Name &amp;&apos;-&apos;&amp; Product__r.Name</formula>
        <inlineHelpText>Client Name &amp;&apos;-&apos;&amp; Product Name</inlineHelpText>
        <label>Client Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>akritiv__Brand__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Req_Id__c</fullName>
        <description>Created it for storing external Id of Applications(Requested by Rajinikanth to create this field)</description>
        <externalId>true</externalId>
        <label>External Request Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MP_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>MP External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Portal_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Client_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_to_Grade__c</fullName>
        <label>Send to Grade</label>
        <summaryFilterItems>
            <field>Debtor__c.Send_to_Grade__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Debtor__c.Client_Account__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Send_to_Portal__c</fullName>
        <label>Send to Portal</label>
        <summaryFilterItems>
            <field>Debtor__c.Send_to_Portal__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Debtor__c.Client_Account__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_with_Grade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Grade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Market_Place__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Market Place</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Client Account</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Client Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MP_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>MP External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Portal_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_with_Grade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Grade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Market_Place__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Market Place</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/ClientAccountBatch_AkritivtoGradePortal.cls
global class ClientAccountBatch_AkritivtoGradePortal implements Database.Batchable<sObject>,Database.Allowscallouts {
    
global Database.QueryLocator Start(Database.BatchableContext BC)
    {
        string query = 'SELECT Id, IsDeleted, Name, CurrencyIsoCode, CreatedDate,Client__c, Product__c, External_Id__c, External_Req_Id__c,';
            query = query+'Portal_External_Id__c, MP_External_Id__c, Sync_with_Grade__c, Sync_with_Market_Place__c, Sync_with_Portal__c,Send_to_Grade__c,Send_to_Portal__c,';
            query = query+'Source__c  FROM Client_Account__c limit 49999';//where (Send_to_Grade__c > 0 or Send_to_Portal__c > 0)
        system.debug('Query ==> '+ query);
        return Database.getQueryLocator(query);
    }
    global Void Execute(Database.BatchableContext BC,list<Client_Account__c> Scope)
    {
        for(Client_Account__c ClientAccount : Scope)
        {
            if(ClientAccount.Send_to_Grade__c > 0 && ClientAccount.External_Id__c != NULL)																														//Sync_with_Portal__c,au
            	TPSSF.TPConnectorService.SubmitExt('Client_Account__c',ClientAccount.Id, '' ,'' ,'sendtograde','akritiv-internex-client_account__c' ,'',UserInfo.getUserId(),UserInfo.getSessionId(),'PartnerUrl', UserInfo.getUserName(), '','','');
            if(ClientAccount.Send_to_Portal__c > 0 && ClientAccount.Portal_External_Id__c != NULL)
             	TPSSF.TPConnectorService.SubmitExt('Client_Account__c',ClientAccount.Id, '' ,'' ,'sendtoportal','akritiv-internex-client_account__c' ,'',UserInfo.getUserId(),UserInfo.getSessionId(),'PartnerUrl', UserInfo.getUserName(), '','','');   
            if(ClientAccount.External_Id__c != NULL)
            TPSSF.TPConnectorService.SubmitExt('Client_Account__c',ClientAccount.Id, '' ,'' ,'sendtompbe','' ,'',UserInfo.getUserId(),UserInfo.getSessionId(),'PartnerUrl', UserInfo.getUserName(), '','','');
        }
    }
    global void Finish(Database.BatchableContext BC)
    {
 	/*	Payments_Batch PB = new Payments_Batch();
        Database.executeBatch(PB, 1); */
    }
}