InternexDev_Sandbox/src/objects/Funding_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Details__c</fullName>
        <label>Bank Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Acceptance_Date__c</fullName>
        <label>CP Funded Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Discount_Interest_Rate__c</fullName>
        <label>Discount/Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Drawal_Fee_Percentage__c</fullName>
        <formula>Funding_Request__r.Client_Account__r.Drawal_Fee_Percentage__c</formula>
        <label>Draw Fee Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Drawal_Fee__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draw Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Fund__c</fullName>
        <label>Funding Allotted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funding_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding Provider</label>
        <referenceTo>Capital_Provider__c</referenceTo>
        <relationshipLabel>Funding Transactions</relationshipLabel>
        <relationshipName>Funding_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Request__c</fullName>
        <label>Funding Request</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.Status</field>
                <operation>equals</operation>
                <value>Fully Funded, Funds Transferred</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Funding Transactions</relationshipLabel>
        <relationshipName>Funding_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Funding_Transaction_Date__c</fullName>
        <label>Funding Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MP_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>MP External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Minimum_Drawal_fee__c</fullName>
        <formula>Funding_Request__r.Client_Account__r.Minimum_Drawal_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Minimum Draw fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Origination_Fee__c</fullName>
        <formula>Funding_Request__r.Client_Account__r.Minimum_Origination_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Minimum Origination Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Origination_Fee_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Origination Fee Applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origination_Fee_Percentage__c</fullName>
        <formula>Funding_Request__r.Client_Account__r.Origination_Fee_Percentage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Origination Fee Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Origination_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Origination Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portal_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sync_with_Grade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Grade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Market_Place__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Market Place</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync with Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Funding Transaction</label>
    <nameField>
        <displayFormat>FT-{00000}</displayFormat>
        <label>Funding Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/Funding_AllocationBatch.cls
global class Funding_AllocationBatch implements Database.Batchable<Sobject>,Database.Allowscallouts{
	global Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query = 'SELECT Id, IsDeleted, Name, CurrencyIsoCode, CreatedDate,Funding_Request__c, Deal_Acceptance_Date__c, Discount_Interest_Rate__c,';
        	   Query = Query + 'Fund__c, Funding_Provider__c, Funding_Transaction_Date__c, External_Id__c, Bank_Details__c, Portal_External_Id__c, MP_External_Id__c,';
        	   query = Query + 'Sync_with_Market_Place__c, Sync_with_Grade__c, Sync_with_Portal__c, Origination_Fee__c, Origination_Fee_Applicable__c,';
			   query = Query + 'Origination_Fee_Percentage__c, Minimum_origination_fee__c, Drawal_Fee__c, Drawal_Fee_Percentage__c, Minimum_Drawal_fee__c';
       		   query = Query + ' FROM Funding_Transaction__c order by Createddate Desc limit 5';
               system.debug('Query ==> '+ query);
        return Database.getQueryLocator(query);
    }
    global Void Execute(Database.BatchableContext BC,list<Funding_Transaction__c> Scope)
    {
		for(Funding_Transaction__c FT : Scope)
        {
            TPSSF.TPConnectorService.SubmitExt('Funding_Transaction__c',FT.Id,'','','sendtoportal','','',UserInfo.getUserId(),UserInfo.getSessionId(),'PartnerUrl', UserInfo.getUserName(), '','','');
        }
    }
    global void Finish(Database.BatchableContext BC)
    {
    }
}