InternexDev_Sandbox/src/objects/Lockbox_Image__c.object
<CustomObject>
    <fields>
        <fullName>Image_Name__c</fullName>
        <label>Image Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>akritiv__Payment__c</referenceTo>
        <relationshipLabel>Payment Images URL</relationshipLabel>
        <relationshipName>Lockbox_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WF_PR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WF_PR</label>
        <referenceTo>WF_PR__c</referenceTo>
        <relationshipLabel>Lockbox Images</relationshipLabel>
        <relationshipName>Lockbox_Images</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lockbox Image</label>
    <nameField>
        <displayFormat>LIN-{000000}</displayFormat>
        <label>Lockbox Image Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lockbox Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/WF_BH__c.object
<CustomObject>
    <fields>
        <fullName>BH_Batch_number__c</fullName>
        <label>Batch number(BH01)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LB_Number__c</fullName>
        <formula>MID(PTH_Lockbox_number__c,2,6)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LB Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTH_Lockbox_number__c</fullName>
        <label>Lockbox number (PTH05)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTH_RDFI_R_T__c</fullName>
        <label>RDFI R/T (PTH02)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTH_RDFI_account_number__c</fullName>
        <label>RDFI account number (PTH03)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WF_FH__c</fullName>
        <label>WF_FH</label>
        <referenceTo>WF_FH__c</referenceTo>
        <relationshipLabel>WF_BH</relationshipLabel>
        <relationshipName>WF_BH</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WF_BH</label>
    <nameField>
        <displayFormat>BH-{00000}</displayFormat>
        <label>WF_BH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF_BH</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/WF_Envelope__c.object
<CustomObject>
    <fields>
        <fullName>Batch_No__c</fullName>
        <label>Batch No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LockBox_Account__c</fullName>
        <label>LockBox Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_No__c</fullName>
        <label>Transaction No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WF Envelope</label>
    <nameField>
        <displayFormat>WFE-{00000}</displayFormat>
        <label>WF Envelope Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF Envelope</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/WF_Invoice_Transactions__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_Account_Number__c</fullName>
        <label>Check Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matching_string_for_Image_mapping__c</fullName>
        <formula>Deposit_date__c + Lockbox_no__c+Batch__c+TEXT(VALUE(Transaction_Number__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Matching string for Image mapping</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WF_Envelope__c</fullName>
        <label>WF Envelope</label>
        <referenceTo>WF_Envelope__c</referenceTo>
        <relationshipLabel>WF Invoice Transactions</relationshipLabel>
        <relationshipName>WF_Invoice_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>WF Invoice Transactions</label>
    <nameField>
        <displayFormat>WFINVT-{00000}</displayFormat>
        <label>WF Invoice Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF Invoice Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/WF_PR__c.object
<CustomObject>
    <fields>
        <fullName>Deposit_settlement_date__c</fullName>
        <label>Deposit/settlement date(PR12)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item_sequence_number__c</fullName>
        <label>Item sequence number (PR01)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matching_string_for_Image_mapping__c</fullName>
        <formula>TEXT(YEAR(Deposit_settlement_date__c))+IF(LEN(TEXT(MONTH(Deposit_settlement_date__c)))= 1,&apos;0&apos;+ TEXT(MONTH(Deposit_settlement_date__c)),TEXT(MONTH(Deposit_settlement_date__c)))+TEXT(DAY(Deposit_settlement_date__c)) + WF_BH__r.LB_Number__c + WF_BH__r.BH_Batch_number__c + TEXT(VALUE(TEXT(Reference_1_PR22B__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Matching string for Image mapping</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reversed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>akritiv__Payment__c</referenceTo>
        <relationshipLabel>WF_PR</relationshipLabel>
        <relationshipName>WF_PR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_method__c</fullName>
        <label>Payment method(PR07)</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FWT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGC</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference_1_PR22B__c</fullName>
        <label>Reference 1(PR22B)</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit Location Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expiration Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Document Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Envelope Sequence Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IBAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Issuer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type of Card or Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WF_BH__c</fullName>
        <label>WF_BH</label>
        <referenceTo>WF_BH__c</referenceTo>
        <relationshipLabel>WF_PR</relationshipLabel>
        <relationshipName>WF_PR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WF_PR</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>WF_PR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF_PR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/WF_Transaction_Data__c.object
<CustomObject>
    <description>This is object stores Wells Fargo transaction data. This file is found in the image zip file. This file extension is .dat</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matching_string_for_Image_mapping__c</fullName>
        <formula>Deposit_date__c + Lockbox_no__c+Batch__c+TEXT(VALUE(Transaction_Number__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Matching string for Image mapping</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WF_Envelope__c</fullName>
        <label>WF Envelope</label>
        <referenceTo>WF_Envelope__c</referenceTo>
        <relationshipLabel>WF Payment Transactions</relationshipLabel>
        <relationshipName>WF_Transaction_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WF_PR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WF_PR</label>
        <referenceTo>WF_PR__c</referenceTo>
        <relationshipLabel>WF Transaction Data</relationshipLabel>
        <relationshipName>WF_Transaction_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WF Transaction Data</label>
    <nameField>
        <displayFormat>WFTD-{00000}</displayFormat>
        <label>Transaction Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF Transaction Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/WF_WP_Transactions__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matching_string_for_Image_mapping__c</fullName>
        <formula>Deposit_date__c + Lockbox_no__c+Batch__c+TEXT(VALUE(Transaction_Number__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Matching string for Image mapping</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WF_Envelope__c</fullName>
        <label>WF Envelope</label>
        <referenceTo>WF_Envelope__c</referenceTo>
        <relationshipLabel>WF WP Transactions</relationshipLabel>
        <relationshipName>WF_WP_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>WF WP Transactions</label>
    <nameField>
        <displayFormat>WFWT-{00000}</displayFormat>
        <label>WF WP Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF WP Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/TestclassforTransactionalData.cls
@istest
public class TestclassforTransactionalData {
	static testmethod void method1()
    {
        WF_FH__c TestFH = new  WF_FH__c();
        insert TestFH;
        
        WF_BH__c TestBH = new WF_BH__c();
        TestBH.WF_FH__c = TestFH.Id;
        TestBH.PTH_Lockbox_number__c= 'HLBNo123';
        TestBH.PTH_RDFI_account_number__c='ty5';
        TestBH.PTH_RDFI_R_T__c='hggh4';
        TestBH.BH_Batch_number__c = 'B1';
        // TestBH.LB_Number__c='fgf4';
        insert TestBH;
        
        WF_PR__c TestPR = new WF_PR__c();
        TestPR.CurrencyIsoCode='USD';
        TestPR.WF_BH__c = TestBH.Id;
        TestPR.Payment_method__c = 'ACH';
        TestPR.Item_sequence_number__c = '1';
        TestPR.Reference_1_PR22B__c = 'T123';
        TestPR.Deposit_settlement_date__c = Date.today();
        // TestPR.Payment_Status__c='None';
        insert TestPR;
        
    //    system.assertEquals(TestPR.Matching_string_for_Image_mapping__c,'2016') ;
        
        list<Lockbox_Image__c> Limagelist = new List<Lockbox_Image__c>();
        Lockbox_Image__c TestLockbox = new Lockbox_Image__c();
        TestLockbox.Image_Name__c = 'FRNTIMAGE_test.jpg';
        //TestLockbox.Payment__c=testPayment.Id;
        //TestLockbox.WF_PR__c=TestPR.Id;
        // TestLockbox.Name='abc';
        Limagelist.add(TestLockbox);
        
        Lockbox_Image__c TestLockbox1 = new Lockbox_Image__c();
        TestLockbox1.Image_Name__c = 'REARIMAGE_test.jpg';
        //TestLockbox.Payment__c=testPayment.Id;
        //TestLockbox.WF_PR__c=TestPR.Id;
        // TestLockbox.Name='abc';
        Limagelist.add(TestLockbox1);
        
        Lockbox_Image__c TestLockbox2 = new Lockbox_Image__c();
        TestLockbox2.Image_Name__c = 'INVIMAGE_test.jpg';
        //TestLockbox.Payment__c=testPayment.Id;
        //TestLockbox.WF_PR__c=TestPR.Id;
        // TestLockbox.Name='abc';
        Limagelist.add(TestLockbox2);
        
        Lockbox_Image__c TestLockbox3 = new Lockbox_Image__c();
        TestLockbox3.Image_Name__c = 'WPIMAGE_test.jpg';
        //TestLockbox.Payment__c=testPayment.Id;
        //TestLockbox.WF_PR__c=TestPR.Id;
        // TestLockbox.Name='abc';
        Limagelist.add(TestLockbox3);
        insert Limagelist;
        
        WF_Envelope__c ENV = new WF_Envelope__c();
        ENV.Batch_No__c = 'B1';
        string mont = string.valueof(Date.today().Month()).length() == 1 ? '0'+string.valueof(Date.today().Month()) : string.valueof(Date.today().Month()) ;
        string customdate = string.valueof(Date.today().year())+ mont +string.valueof(Date.today().DAY());
        ENV.Date__c = customdate;
        ENV.LockBox_Account__c = 'LBNo12';
        ENV.Transaction_No__c = '123';
        insert ENV;
        
        WF_Transaction_Data__c WFT = new WF_Transaction_Data__c();
        WFT.Action__c = 'A';
        WFT.Check_Account_Number__c = 'CHK123';
        WFT.Check_Amount__c = '1.50';
        WFT.Check_Date__c = customdate;
        WFT.Check_RTN__c = 'CHKRTN123';
        WFT.Custom_Data__c = 'Custom Data';
        WFT.Deposit_date__c = customdate;
        WFT.Lockbox_no__c = 'LBNo12';
        WFT.Batch__c = 'B1';
        WFT.Transaction_Number__c = '123';
        
        WFT.Depository_Account__c = 'DA123';
        WFT.Front_image_file__c = 'FRNTIMAGE_test.jpg';
        WFT.Rear_Image_File__c = 'REARIMAGE_test.jpg';
        WFT.Invoice_amount__c = '1.50';
        WFT.Invoice_Number__c = 'INV123';
        WFT.Record_Type__c = 'CHK';
        WFT.Remitter_Name__c = 'REMIT123';
        WFT.Sequence_Number__c = '1';
        WFT.Serial_Number__c = 'SL12';
        insert WFT;
        
        WF_Invoice_Transactions__c WFIT = new WF_Invoice_Transactions__c();
        WFIT.Action__c = 'A';
        WFIT.Check_Account_Number__c = 'CHK123';
        WFIT.Check_Amount__c = '1.50';
        WFIT.Check_Date__c = customdate;
        WFIT.Check_RTN__c = 'CHKRTN123';
        WFIT.Custom_Data__c = 'Custom Data';
        WFIT.Deposit_date__c = customdate;
        WFIT.Lockbox_no__c = 'LBNo12';
        WFIT.Batch__c = 'B1';
        WFIT.Transaction_Number__c = '123';
        
        WFIT.Depository_Account__c = 'DA123';
        WFIT.Front_image_file__c = 'INVIMAGE_test.jpg';
        WFIT.Rear_Image_File__c = 'INVIMAGE_test.jpg';
        WFIT.Invoice_amount__c = '1.50';
        WFIT.Invoice_Number__c = 'INV123';
        WFIT.Record_Type__c = 'CHK';
        WFIT.Remitter_Name__c = 'REMIT123';
        WFIT.Sequence_Number__c = '1';
        WFIT.Serial_Number__c = 'SL12';
        insert WFIT;
        
        WF_WP_Transactions__c WFWPT = new WF_WP_Transactions__c();
        WFWPT.Action__c = 'A';
        WFWPT.Check_Account_Number__c = 'CHK123';
        WFWPT.Check_Amount__c = '1.50';
        WFWPT.Check_Date__c = customdate;
        WFWPT.Check_RTN__c = 'CHKRTN123';
        WFWPT.Custom_Data__c = 'Custom Data';
        WFWPT.Deposit_date__c = customdate;
        WFWPT.Lockbox_no__c = 'LBNo12';
        WFWPT.Batch__c = 'B1';
        WFWPT.Transaction_Number__c = '123';
        
        WFWPT.Depository_Account__c = 'DA123';
        WFWPT.Front_image_file__c = 'WPIMAGE_test.jpg';
        WFWPT.Rear_Image_File__c = 'WPIMAGE_test.jpg';
        WFWPT.Invoice_amount__c = '1.50';
        WFWPT.Invoice_Number__c = 'INV123';
        WFWPT.Record_Type__c = 'CHK';
        WFWPT.Remitter_Name__c = 'REMIT123';
        WFWPT.Sequence_Number__c = '1';
        WFWPT.Serial_Number__c = 'SL12';
        insert WFWPT;
  
    }
}