InternexDev_Sandbox/src/objects/WF_BH__c.object
<CustomObject>
    <fields>
        <fullName>BH_Batch_number__c</fullName>
        <label>Batch number(BH01)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LB_Number__c</fullName>
        <formula>MID(PTH_Lockbox_number__c,2,6)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LB Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTH_Lockbox_number__c</fullName>
        <label>Lockbox number (PTH05)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTH_RDFI_R_T__c</fullName>
        <label>RDFI R/T (PTH02)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTH_RDFI_account_number__c</fullName>
        <label>RDFI account number (PTH03)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WF_FH__c</fullName>
        <label>WF_FH</label>
        <referenceTo>WF_FH__c</referenceTo>
        <relationshipLabel>WF_BH</relationshipLabel>
        <relationshipName>WF_BH</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WF_BH</label>
    <nameField>
        <displayFormat>BH-{00000}</displayFormat>
        <label>WF_BH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF_BH</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/WF_FH__c.object
<CustomObject>
    <label>WF_FH</label>
    <nameField>
        <displayFormat>FH-{00000}</displayFormat>
        <label>WF_FH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF_FH</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/objects/WF_PR__c.object
<CustomObject>
    <fields>
        <fullName>Additional_currency_code__c</fullName>
        <label>Additional currency code(PR19)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Additional_entity_identifier_code__c</fullName>
        <label>Additional entity identifier code(PR18)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount_paid__c</fullName>
        <label>Amount paid(PR05)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit_debit_indicator__c</fullName>
        <description>Indicates whether the payment is a credit (C) or debit (D).</description>
        <label>Credit/debit indicator(PR04)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_code__c</fullName>
        <label>Currency code(PR16)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_entity_identifier_code__c</fullName>
        <label>Currency entity identifier code(PR15)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_market_exchange_code__c</fullName>
        <label>Currency market/ exchange code(PR20)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Amount_1__c</fullName>
        <label>Custom Amount 1(PR31)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deposit_settlement_date__c</fullName>
        <label>Deposit/settlement date(PR12)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exchange_rate__c</fullName>
        <label>Exchange rate(PR17)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_amount__c</fullName>
        <label>Gross amount(PR06)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_sequence_number__c</fullName>
        <label>Item sequence number (PR01)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCA_Amount_Paid__c</fullName>
        <label>MCA Amount Paid(PR32)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ODFI_RTN__c</fullName>
        <label>ODFI RTN(PR02)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ODFI_account_number_ACH_company_ID_con__c</fullName>
        <inlineHelpText>PR03</inlineHelpText>
        <label>ODFI account number/ ACH company ID/ con</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reversed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_effective_date__c</fullName>
        <label>Payment effective date(PR13)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_method__c</fullName>
        <label>Payment method(PR07)</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FWT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CWT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGC</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_method_type_code__c</fullName>
        <label>Payment method type code(PR08)</label>
        <picklist>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IAT</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Processing_system_reference_number__c</fullName>
        <label>Processing system reference number(PR10)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <defaultValue>&quot;PR&quot;</defaultValue>
        <label>Record ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_1_PR22B__c</fullName>
        <label>Reference 1(PR22B)</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit Location Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expiration Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Document Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Envelope Sequence Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IBAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Issuer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type of Card or Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference_1_description__c</fullName>
        <label>Reference 1 description(PR22A)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_1_qualifier_description__c</fullName>
        <label>Reference 1 qualifier/description(PR21)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_2__c</fullName>
        <label>Reference 2(PR24B)</label>
        <picklist>
            <picklistValues>
                <fullName>Receiver Reference Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Pay Reason Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WASAU Sequence Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FX Contract Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WPIC Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Batch ID</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference_2_description__c</fullName>
        <label>Reference 2 description(PR24A)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_2_qualifier_description_PR__c</fullName>
        <label>Reference 2 qualifier/description(PR23)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_3__c</fullName>
        <label>Reference 3(PR26)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_3_qualifier_description__c</fullName>
        <label>Reference 3 qualifier/description(PR25)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_4__c</fullName>
        <label>Reference 4(PR28)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_4_qualifier_description__c</fullName>
        <label>Reference 4 qualifier/description(PR27)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_5__c</fullName>
        <label>Reference 5(PR29)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_6__c</fullName>
        <label>Reference 6(PR30)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reversal_Reason_Code__c</fullName>
        <label>Reversal Reason Code(PR34)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_payment_reference_number__c</fullName>
        <label>Sender payment reference number(PR09)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_BH__c</fullName>
        <label>Temp BH</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_processing_date_time__c</fullName>
        <label>Transaction processing date/time(PR14)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WF_BH__c</fullName>
        <label>WF_BH</label>
        <referenceTo>WF_BH__c</referenceTo>
        <relationshipLabel>WF_PR</relationshipLabel>
        <relationshipName>WF_PR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wells_Fargo_reference_number__c</fullName>
        <label>Wells Fargo reference number(PR11)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>WF_PR</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>WF_PR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF_PR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InternexDev_Sandbox/src/classes/TestLockBox.cls
@istest
public class TestLockBox
{
    static testmethod void lockbox()
    {
        
         WF_FH__c TestFH = new  WF_FH__c();
        insert TestFH;
        
        WF_BH__c TestBH = new WF_BH__c();
        TestBH.WF_FH__c = TestFH.Id;
        TestBH.PTH_Lockbox_number__c='5tt';
        TestBH.PTH_RDFI_account_number__c='ty5';
        TestBH.PTH_RDFI_R_T__c='hggh4';
        TestBH.BH_Batch_number__c = '1000';
        // TestBH.LB_Number__c='fgf4';
        insert TestBH;
        
        WF_PR__c wf = new WF_PR__c();
        wf.Amount_paid__c =100;
        wf.WF_BH__c = TestBH.Id;
        
       // wf.IsDeleted = false;
      //  wf.Name = 'abc';
        wf.CurrencyIsoCode ='INR';
       // wf.SystemModstamp = system.now();
        wf.Record_ID__c= 'rec';
        wf.Item_sequence_number__c = 'seq';
        wf.ODFI_RTN__c ='rtn';
        wf.ODFI_account_number_ACH_company_ID_con__c='acc';
        wf.Credit_debit_indicator__c='creditDebit';
        wf.Amount_paid__c=100;
        wf.Gross_amount__c=200;
        wf.Payment_method__c='ACH';
        wf.Payment_method_type_code__c='D';
        wf.Sender_payment_reference_number__c='num';
        wf.Processing_system_reference_number__c='pro';
        wf.Wells_Fargo_reference_number__c='wells';
        wf.Deposit_settlement_date__c=date.today();
        wf.Payment_effective_date__c=date.today();
        wf.Transaction_processing_date_time__c=system.now();
        wf.Currency_entity_identifier_code__c='code';
        wf.Currency_code__c='INR';
        wf.Exchange_rate__c=10;
        wf.Additional_entity_identifier_code__c='add';
        wf.Additional_currency_code__c='currency';
        wf.Currency_market_exchange_code__c='mar';
        wf.Reference_1_qualifier_description__c='des';
        wf.Reference_1_description__c='reff';
        wf.Reference_1_PR22B__c='Account Number';
        wf.Reference_2_qualifier_description_PR__c='pr';
        wf.Reference_2_description__c='desc';
        wf.Reference_2__c='Batch ID';
        wf.Reference_3_qualifier_description__c='abbbvvd';
        wf.Reference_3__c='ddd';
        wf.Reference_4_qualifier_description__c='fff';
        wf.Reference_4__c='jjj';
        wf.Reference_5__c='fibe';
        wf.Reference_6__c ='ref';
        wf.Custom_Amount_1__c=10;
        wf.MCA_Amount_Paid__c=100;
        wf.Gross_amount__c=200;
        wf.Reversal_Reason_Code__c='rev';
        wf.Temp_BH__c='temp';
        wf.Payment_Status__c='valid'; 
        insert wf;
        
         Test.startTest();
        SchedulableContext ctx;
        LockboxScheduler IB = new LockboxScheduler();
        IB.execute(ctx);
       
        Test.stopTest(); 
        
        
        
    }

}